version: "3.8"

services:
    frontend:
        build: .
        image: erp-frontend-app
        container_name: erp-frontend-app
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3001:3000"
        command: npm run dev -- -p 3000
