from .markup_template import MarkupTemplate

class ExperienceCertificate(MarkupTemplate):

    class Meta:
        db_table = "experience_certificates"

    def __str__(self) -> str:
        return f"ExperienceCertificate ({self.lang})"

    @staticmethod
    def default_exp_certificate():
        default_template = {
            'ar': (
                '<h3 style="text-align: center;">بريد إلكتروني تجربة</h3>'
                '<p>{app_name}</p>'
                '<p>إلي من يهمه الامر</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>مدة الخدمة {duration} في {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>الادوار والمسؤوليات</p>'
                '<p>وصف موجز لمسار عمل الموظف وبيان إيجابي من المدير أو المشرف.</p>'
                '<p>بإخلاص،</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>التوقيع</p>'
                '<p>{app_name}</p>'
            ),
            'zh': (
                '<p lang="en-IN" style="margin-bottom: 0cm; direction: ltr; line-height: 2; text-align: center;" align="center">'
                '<span style="font-size: 18pt;"><strong>经验信</strong></span></p>'
                '<p align="center">{app_name}</p>'
                '<p align="center">可能涉及的人</p>'
                '<p align="center">{date}</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{app_name} 中的服务期限为 {duration}。</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">{payroll}</p>'
                '<p align="center">角色和职责</p>'
                '<p align="center">员工工作经历的简要描述以及经理或主管的积极评价。</p>'
                '<p align="center">真诚的，</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">签名</p>'
                '<p align="center">{app_name}</p>'
            ),
            'da': (
                '<h3 style="text-align: center;">Erfaringsbrev</h3>'
                '<p>{app_name}</p>'
                '<p>TIL HVEM DET MÅTTE VEDRØRE</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tjenesteperiode {duration} i {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Roller og ansvar</p>'
                '<p>Kort beskrivelse af medarbejderens ansættelsesforløb og positiv udtalelse fra leder eller arbejdsleder.</p>'
                '<p>Med venlig hilsen</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Underskrift</p>'
                '<p>{app_name}</p>'
            ),
            'de': (
                '<h3 style="text-align: center;">Erfahrungsbrief</h3>'
                '<p>{app_name}</p>'
                '<p>WEN ES ANGEHT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Dienstzeit {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rollen und Verantwortlichkeiten</p>'
                '<p>Kurze Beschreibung des beruflichen Werdegangs des Mitarbeiters und eine positive Stellungnahme des Vorgesetzten oder Vorgesetzten.</p>'
                '<p>Aufrichtig,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Unterschrift</p>'
                '<p>{app_name}</p>'
            ),
            'en': (
                '<p style="text-align: center;"><span style="font-size: 18pt;"><strong>Experience Letter</strong></span></p>'
                '<p>Date: {date}</p>'
                '<p>To Whom It May Concern</p>'
                '<p>This letter is to certify the experience of {employee_name}.</p>'
                '<p>Tenure of Service {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Roles and Responsibilities</p>'
                '<p>Brief description of the employee’s course of employment and a positive statement from the manager or supervisor.</p>'
                '<p>Sincerely,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Signature</p>'
                '<p>{app_name}</p>'
            ),
            'es': (
                '<h3 style="text-align: center;">Carta de experiencia</h3>'
                '<p>{app_name}</p>'
                '<p>A QUIEN LE INTERESE</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Duración del servicio {duration} en {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Funciones y responsabilidades</p>'
                '<p>Breve descripción del curso de empleo del empleado y una declaración positiva del gerente o supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Firma</p>'
                '<p>{app_name}</p>'
            ),
            'fr': (
                '<h3 style="text-align: center;">Lettre d’expérience</h3>'
                '<p>{app_name}</p>'
                '<p>À QUI DE DROIT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Durée du service {duration} dans {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rôles et responsabilités</p>'
                '<p>Brève description de l’évolution de l’emploi de l’employé et une déclaration positive du gestionnaire ou superviseur.</p>'
                '<p>Sincèrement,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Signature</p>'
                '<p>{app_name}</p>'
            ),
            'he': (
                '<p style="text-align: center;"><span style="font-size: 18pt;"><strong>מכתב ניסיון</strong></span></p>'
                '<p>תאריך: {date}</p>'
                '<p>למי שזה עשוי להדאיג</p>'
                '<p>{employee_name}</p>'
                '<p>תקופת השירות {duration} ב-{app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>תפקידים ואחריות</p>'
                '<p>תיאור קצר של מהלך העסקתו של העובד והצהרה חיובית מהמנהל או הממונה.</p>'
                '<p>בברכה,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>חתימה</p>'
                '<p>{app_name}</p>'
            ),
            'it': (
                '<h3 style="text-align: center;">Lettera di esperienza</h3>'
                '<p>{app_name}</p>'
                '<p>PER CHI È COINVOLTO</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Durata del servizio {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Ruoli e responsabilità</p>'
                '<p>Breve descrizione del percorso lavorativo del dipendente e dichiarazione positiva del manager o supervisore.</p>'
                '<p>Cordiali saluti,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Firma</p>'
                '<p>{app_name}</p>'
            ),
            'ja': (
                '<h3 style="text-align: center;">体験談</h3>'
                '<p>{app_name}</p>'
                '<p>ご担当者様</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>{app_name} のサービス {duration} の保有期間。</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>役割と責任</p>'
                '<p>従業員の雇用コースの簡単な説明と、マネージャーまたはスーパーバイザーからの肯定的な声明。</p>'
                '<p>心から、</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>サイン</p>'
                '<p>{app_name}</p>'
            ),
            'nl': (
                '<h3 style="text-align: center;">Ervaringsbrief</h3>'
                '<p>{app_name}</p>'
                '<p>VOOR WIE HET AANGAAT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Diensttijd {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rollen en verantwoordelijkheden</p>'
                '<p>Korte omschrijving van het dienstverband van de medewerker en een positieve verklaring van de leidinggevende.</p>'
                '<p>Eerlijk,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Handtekening</p>'
                '<p>{app_name}</p>'
            ),
            'pl': (
                '<h3 style="text-align: center;">Doświadczenie List</h3>'
                '<p>{app_name}</p>'
                '<p>DO TYCH KTÓRYCH MOŻE TO DOTYCZYĆ</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Okres świadczenia usług {duration} w {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Role i obowiązki</p>'
                '<p>Krótki opis przebiegu zatrudnienia pracownika oraz pozytywna opinia kierownika lub przełożonego.</p>'
                '<p>Z poważaniem,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Podpis</p>'
                '<p>{app_name}</p>'
            ),
            'pt': (
                '<h3 style="text-align: center;">Carta de Experiência</h3>'
                '<p>{app_name}</p>'
                '<p>A QUEM POSSA INTERESSAR</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tempo de serviço {duration} em {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Papéis e responsabilidades</p>'
                '<p>Breve descrição do curso de emprego do funcionário e uma declaração positiva do gerente ou supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Assinatura</p>'
                '<p>{app_name}</p>'
            ),
            'ru': (
                '<h3 style="text-align: center;">Письмо об опыте</h3>'
                '<p>{app_name}</p>'
                '<p>ДЛЯ ПРЕДЪЯВЛЕНИЯ ПО МЕСТУ ТРЕБОВАНИЯ</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Срок службы {duration} в {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Роли и обязанности</p>'
                '<p>Краткое описание трудового стажа работника и положительное заключение руководителя.</p>'
                '<p>Искренне,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Подпись</p>'
                '<p>{app_name}</p>'
            ),
            'tr': (
                '<p style="text-align: center;"><span style="font-size: 18pt;"><strong>Deneyim Mektubu</strong></span></p>'
                '<p>Tarih: {tarih}</p>'
                '<p>İLGİLENEN KİMİN İÇİN</p>'
                '<p>{tarih}</p>'
                '<p>{çalışan_adı}</p>'
                '<p>Hizmet Kullanım Süresi {duration}, {app_name} uygulamasında.</p>'
                '<p>{tanımlama}</p>'
                '<p>{bordro}</p>'
                '<p>Roller ve Sorumluluklar</p>'
                '<p>Çalışanların çalışma şekline ilişkin kısa açıklama ve yönetici veya süpervizörden olumlu bir açıklama.</p>'
                '<p>Saygılarımızla,</p>'
                '<p>{çalışan_adı}</p>'
                '<p>{tanımlama}</p>'
                '<p>İmza</p>'
                '<p>{uygulama_adı}</p>'
            ),
            'pt-br': (
                '<h3 style="text-align: center;">Carta de Experiência</h3>'
                '<p>{app_name}</p>'
                '<p>A QUEM POSSA INTERESSAR</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tempo de serviço {duration} em {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Papéis e responsabilidades</p>'
                '<p>Breve descrição do curso de emprego do funcionário e uma declaração positiva do gerente ou supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Assinatura</p>'
                '<p>{app_name}</p>'
            ),
        }
        for lang_key, content in default_template.items():
            ExperienceCertificate.objects.create(
                lang=lang_key,
                content=content,
                created_by=2,
            )

    @staticmethod
    def default_exp_certificate_register(user_id):
        default_template = {
            'ar': (
                '<h3 style="text-align: center;">بريد إلكتروني تجربة</h3>'
                '<p>{app_name}</p>'
                '<p>إلي من يهمه الامر</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>مدة الخدمة {duration} في {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>الادوار والمسؤوليات</p>'
                '<p>وصف موجز لمسار عمل الموظف وبيان إيجابي من المدير أو المشرف.</p>'
                '<p>بإخلاص،</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>التوقيع</p>'
                '<p>{app_name}</p>'
            ),
            'zh': (
                '<p lang="en-IN" style="margin-bottom: 0cm; direction: ltr; line-height: 2; text-align: center;" align="center">'
                '<span style="font-size: 18pt;"><strong>经验信</strong></span></p>'
                '<p align="center">{app_name}</p>'
                '<p align="center">可能涉及的人</p>'
                '<p align="center">{date}</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{app_name} 中的服务期限为 {duration}。</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">{payroll}</p>'
                '<p align="center">角色和职责</p>'
                '<p align="center">员工工作经历的简要描述以及经理或主管的积极评价。</p>'
                '<p align="center">真诚的，</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">签名</p>'
                '<p align="center">{app_name}</p>'
            ),
            'da': (
                '<h3 style="text-align: center;">Erfaringsbrev</h3>'
                '<p>{app_name}</p>'
                '<p>TIL HVEM DET MÅTTE VEDRØRE</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tjenesteperiode {duration} i {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Roller og ansvar</p>'
                '<p>Kort beskrivelse af medarbejderens ansættelsesforløb og positiv udtalelse fra leder eller arbejdsleder.</p>'
                '<p>Med venlig hilsen</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Underskrift</p>'
                '<p>{app_name}</p>'
            ),
            'de': (
                '<h3 style="text-align: center;">Erfahrungsbrief</h3>'
                '<p>{app_name}</p>'
                '<p>WEN ES ANGEHT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Dienstzeit {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rollen und Verantwortlichkeiten</p>'
                '<p>Kurze Beschreibung des beruflichen Werdegangs des Mitarbeiters und eine positive Stellungnahme des Vorgesetzten oder Vorgesetzten.</p>'
                '<p>Aufrichtig,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Unterschrift</p>'
                '<p>{app_name}</p>'
            ),
            'en': (
                '<p lang="en-IN" style="margin-bottom: 0cm; direction: ltr; line-height: 2; text-align: center;" align="center">'
                '<span style="font-size: 18pt;"><strong>Experience Letter</strong></span></p>'
                '<p align="center">{app_name}</p>'
                '<p align="center">TO WHOM IT MAY CONCERN</p>'
                '<p align="center">{date}</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">Tenure of Service {duration} in {app_name}.</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">{payroll}</p>'
                '<p align="center">Roles and Responsibilities</p>'
                '<p align="center">Brief description of the employee’s course of employment and a positive statement from the manager or supervisor.</p>'
                '<p align="center">Sincerely,</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">Signature</p>'
                '<p align="center">{app_name}</p>'
            ),
            'es': (
                '<h3 style="text-align: center;">Carta de experiencia</h3>'
                '<p>{app_name}</p>'
                '<p>A QUIEN LE INTERESE</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Duración del servicio {duration} en {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Funciones y responsabilidades</p>'
                '<p>Breve descripción del curso de empleo del empleado y una declaración positiva del gerente o supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Firma</p>'
                '<p>{app_name}</p>'
            ),
            'fr': (
                '<h3 style="text-align: center;">Lettre d’expérience</h3>'
                '<p>{app_name}</p>'
                '<p>À QUI DE DROIT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Durée du service {duration} dans {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rôles et responsabilités</p>'
                '<p>Brève description de l’évolution de l’emploi de l’employé et une déclaration positive du gestionnaire ou superviseur.</p>'
                '<p>Sincèrement,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Signature</p>'
                '<p>{app_name}</p>'
            ),
            'he': (
                '<p lang="en-IN" style="margin-bottom: 0cm; direction: ltr; line-height: 2; text-align: center;" align="center">'
                '<span style="font-size: 18pt;"><strong>מכתב ניסיון</strong></span></p>'
                '<p align="center">{app_name}</p>'
                '<p align="center">למי זה עשוי להדאיג</p>'
                '<p align="center">{date}</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">תקופת השירות {duration} ב-{app_name}.</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">{payroll}</p>'
                '<p align="center">תפקידים ואחריות</p>'
                '<p align="center">תיאור קצר של מהלך העסקתו של העובד והצהרה חיובית מהמנהל או הממונה.</p>'
                '<p align="center">בברכה,</p>'
                '<p align="center">{employee_name}</p>'
                '<p align="center">{designation}</p>'
                '<p align="center">חתימה</p>'
                '<p align="center">{app_name}</p>'
            ),
            'it': (
                '<h3 style="text-align: center;">Lettera di esperienza</h3>'
                '<p>{app_name}</p>'
                '<p>PER CHI È COINVOLTO</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Durata del servizio {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Ruoli e responsabilità</p>'
                '<p>Breve descrizione del percorso lavorativo del dipendente e dichiarazione positiva del manager o supervisore.</p>'
                '<p>Cordiali saluti,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Firma</p>'
                '<p>{app_name}</p>'
            ),
            'ja': (
                '<h3 style="text-align: center;">体験談</h3>'
                '<p>{app_name}</p>'
                '<p>ご担当者様</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>{app_name} のサービス {duration} の保有期間。</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>役割と責任</p>'
                '<p>従業員の雇用コースの簡単な説明と、マネージャーまたはスーパーバイザーからの肯定的な声明。</p>'
                '<p>心から、</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>サイン</p>'
                '<p>{app_name}</p>'
            ),
            'nl': (
                '<h3 style="text-align: center;">Ervaringsbrief</h3>'
                '<p>{app_name}</p>'
                '<p>VOOR WIE HET AANGAAT</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Diensttijd {duration} in {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Rollen en verantwoordelijkheden</p>'
                '<p>Korte omschrijving van het dienstverband van de medewerker en een positieve verklaring van de leidinggevende.</p>'
                '<p>Eerlijk,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Handtekening</p>'
                '<p>{app_name}</p>'
            ),
            'pl': (
                '<h3 style="text-align: center;">Doświadczenie List</h3>'
                '<p>{app_name}</p>'
                '<p>DO TYCH KTÓRYCH MOŻE TO DOTYCZYĆ</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Okres świadczenia usług {duration} w {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Role i obowiązki</p>'
                '<p>Krótki opis przebiegu zatrudnienia pracownika oraz pozytywna opinia kierownika lub przełożonego.</p>'
                '<p>Z poważaniem,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Podpis</p>'
                '<p>{app_name}</p>'
            ),
            'pt': (
                '<h3 style="text-align: center;">Carta de Experiência</h3>'
                '<p>{app_name}</p>'
                '<p>A QUEM POSSA INTERESSAR</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tempo de serviço {duration} em {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Papéis e responsabilidades</p>'
                '<p>Breve descrição do curso de emprego do funcionário e uma declaração positiva do gerente ou supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Assinatura</p>'
                '<p>{app_name}</p>'
            ),
            'ru': (
                '<h3 style="text-align: center;">Письмо об опыте</h3>'
                '<p>{app_name}</p>'
                '<p>ДЛЯ ПРЕДЪЯВЛЕНИЯ ПО МЕСТУ ТРЕБОВАНИЯ</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Срок службы {duration} в {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Роли и обязанности</p>'
                '<p>Краткое описание трудового стажа работника и положительное заключение руководителя.</p>'
                '<p>Искренне,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Подпись</p>'
                '<p>{app_name}</p>'
            ),
            'tr': (
                '<p lang="en-IN" style="margin-bottom: 0cm; direction: ltr; line-height: 2; text-align: center;" align="center">'
                '<span style="font-size: 18pt;"><strong>Deneyim Mektubu</strong></span></p>'
                '<p align="center">{uygulama_adı}</p>'
                '<p align="center">İLGİLENEN KİMİN İÇİN</p>'
                '<p align="center">{tarih}</p>'
                '<p align="center">{çalışan_adı}</p>'
                '<p align="center">Hizmet Kullanım Süresi {duration}, {app_name} uygulamasında.</p>'
                '<p align="center">{tanımlama}</p>'
                '<p align="center">{bordro}</p>'
                '<p align="center">Roller ve Sorumluluklar</p>'
                '<p align="center">Çalışanların çalışma şekline ilişkin kısa açıklama ve yönetici veya süpervizörden olumlu bir açıklama.</p>'
                '<p align="center">Saygılarımızla,</p>'
                '<p align="center">{çalışan_adı}</p>'
                '<p align="center">{tanımlama}</p>'
                '<p align="center">İmza</p>'
                '<p align="center">{uygulama_adı}</p>'
            ),
            'pt-br': (
                '<h3 style="text-align: center;">Carta de Experiência</h3>'
                '<p>{app_name}</p>'
                '<p>A QUEM POSSA INTERESSAR</p>'
                '<p>{date}</p>'
                '<p>{employee_name}</p>'
                '<p>Tempo de serviço {duration} em {app_name}.</p>'
                '<p>{designation}</p>'
                '<p>{payroll}</p>'
                '<p>Papéis e responsabilidades</p>'
                '<p>Breve descrição do curso de emprego do funcionário e uma declaração positiva do gerente ou supervisor.</p>'
                '<p>Sinceramente,</p>'
                '<p>{employee_name}</p>'
                '<p>{designation}</p>'
                '<p>Assinatura</p>'
                '<p>{app_name}</p>'
            ),
        }
        for lang_key, content in default_template.items():
            ExperienceCertificate.objects.create(
                lang=lang_key,
                content=content,
                created_by=user_id,
            )
