/**
 * Playwright E2E spec for Ai Generate Lang Copy (lang route).
 * Auto-generated by generate-lang-harness.cjs
 */

import { test, expect } from "@playwright/test";

const PAGE = "http://localhost:3333/harness/pages/ai-generate-lang-copy.html";

test.describe("Ai Generate Lang Copy", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE);
  });

  test("page loads without console errors", async ({ page }) => {
    const errors: string[] = [];
    page.on("console", (msg) => {
      if (msg.type() === "error") errors.push(msg.text());
    });
    await page.waitForLoadState("networkidle");
    expect(errors).toHaveLength(0);
  });

  test("has correct title", async ({ page }) => {
    const heading = page.locator('[data-testid="page-title"]');
    await expect(heading).toBeVisible();
    await expect(heading).toContainText("Ai Generate Lang Copy");
  });

  test("translations object exists on window", async ({ page }) => {
    const translations = await page.evaluate(() => (window as unknown as Record<string, unknown>).translations);
    expect(translations).toBeDefined();
    expect(typeof translations).toBe("object");
  });
});
