alias ..='cd ..'
alias ...='cd ../..'
alias .ilv='cd _inc/laravel'
alias grep='grep --color=auto'
alias artmrs='php artisan migrate:reset'
alias artmsd='php artisan migrate:fresh --seed'
alias artmst='php artisan migrate:status'
alias artmrs-sd='php artisan migrate:status && php artisan migrate:reset && php artisan migrate:fresh --seed'
alias artcl='php artisan config:clear && php artisan cache:clear && php artisan optimize:clear && php artisan route:clear && php artisan view:clear && php artisan clear-compiled'
alias laravel-rm-cache='rm -f bootstrap/cache/services.php && rm -f bootstrap/cache/packages.php && rm -f bootstrap/cache/compiled.php && rm -f bootstrap/cache/routes.php'
alias compdp='composer dump-autoload -o'
alias mysqlr='mysql -u root -p'