/**
 * Jest unit test for indicators-lang-index (lang route).
 * Auto-generated by generate-lang-harness.cjs
 *
 * @jest-environment jsdom
 */

describe("indicators-lang-index", () => {
  beforeEach(() => {
    document.body.innerHTML = `
      <div id="app">
        <div id="content"></div>
        <div id="toast-container"></div>
      </div>
    `;
    (window as unknown as Record<string, unknown>).translations = {};
  });

  test("module can be imported without throwing", async () => {
    await expect(import("../../src/public/assets/js/routes/indicators/lang/index.ts")).resolves.toBeDefined();
  });

  test("window.translations is populated after import", async () => {
    await import("../../src/public/assets/js/routes/indicators/lang/index.ts");
    const t = (window as unknown as Record<string, unknown>).translations;
    expect(t).toBeDefined();
    expect(typeof t).toBe("object");
  });
});
