/**
 * Jest unit test for invoices-customers-lang-view (lang route).
 * Auto-generated by generate-lang-harness.cjs
 *
 * @jest-environment jsdom
 */

describe("invoices-customers-lang-view", () => {
  beforeEach(() => {
    document.body.innerHTML = `
      <div id="app">
        <div id="content"></div>
        <div id="toast-container"></div>
      </div>
    `;
    (window as unknown as Record<string, unknown>).translations = {};
    // Mock globals that the route file depends on
    (window as unknown as Record<string, unknown>).is_page = () => true;
  });

  test("module can be imported without throwing", async () => {
    await expect(import("../../src/public/assets/js/routes/invoices/customers/lang/view.ts")).resolves.toBeDefined();
  });

  test("window.translations is populated after import", async () => {
    await import("../../src/public/assets/js/routes/invoices/customers/lang/view.ts");
    const t = (window as unknown as Record<string, unknown>).translations;
    expect(t).toBeDefined();
    expect(typeof t).toBe("object");
  });
});
