<?php

namespace App\Config\Constants;

class FormsConstants
{
	public const PERMISSIONS = [
		PermissionsConstants::MNG_FM_BD,
		'create form builder',
		'edit form builder',
		'delete form builder',
		'manage form field',
		'create form field',
		'edit form field',
		'delete form field',
		'view form response',
		PermissionsConstants::MNG_PRF_TP,
		PermissionsConstants::CRT_PRF_TP,
		PermissionsConstants::ED_PRF_TP,
		PermissionsConstants::DEL_PRF_TP,
		'manage budget plan',
		'create budget plan',
		'edit budget plan',
		'delete budget plan',
		'view budget plan',
		PermissionsConstants::STK_RPT,
		PermissionsConstants::MNG_WRH,
		'create warehouse',
		'edit warehouse',
		'show warehouse',
		'delete warehouse',
		PermissionsConstants::MNG_PRC,
		'create purchase',
		'edit purchase',
		'view purchase',
		'show purchase',
		'delete purchase',
		'send purchase',
		'create payment purchase',
		PermissionsConstants::MNG_POS,
		'manage contract type',
		'create contract type',
		'edit contract type',
		'delete contract type',
		PermissionsConstants::CR_BC,
		PermissionsConstants::SHW_CRM_DSB,
		'share project',
		PermissionsConstants::SHW_POS_DSB,
		'create webhook',
		PermissionsConstants::ED_WHK,
		PermissionsConstants::DEL_WHK,
	];
	public const COMPANY_PERMISSIONS = [
		PermissionsConstants::MNG_FM_BD,
		'create form builder',
		'edit form builder',
		'delete form builder',
		'manage form field',
		'create form field',
		'edit form field',
		'delete form field',
		'view form response',
		PermissionsConstants::MNG_PRF_TP,
		PermissionsConstants::CRT_PRF_TP,
		PermissionsConstants::ED_PRF_TP,
		PermissionsConstants::DEL_PRF_TP,
		'manage budget plan',
		'create budget plan',
		'edit budget plan',
		'delete budget plan',
		'view budget plan',
		PermissionsConstants::STK_RPT,
		PermissionsConstants::MNG_WRH,
		'create warehouse',
		'edit warehouse',
		'show warehouse',
		'delete warehouse',
		PermissionsConstants::MNG_PRC,
		'create purchase',
		'edit purchase',
		'show purchase',
		'delete purchase',
		'send purchase',
		'create payment purchase',
		PermissionsConstants::MNG_POS,
		'manage contract type',
		'create contract type',
		'edit contract type',
		'delete contract type',
		PermissionsConstants::CR_BC,
		PermissionsConstants::SHW_CRM_DSB,
		'share project',
		PermissionsConstants::SHW_POS_DSB,
		'create webhook',
		PermissionsConstants::ED_WHK,
		PermissionsConstants::DEL_WHK,
	];
}
