<?php

namespace App\Config\Constants;

class ProjectsConstants
{
	public const COL_PJ_ID = 'project_id';
	public const COL_PJ_TSK_ID = 'project_task_id';
	public const COL_ASGN = 'assign_to';
	public const COL_ML_ID = 'milestone_id';
	public const COL_PPL_ID = 'pipeline_id';
	public const COL_CL = 'color';
	public const COL_NM = 'name';
	public const COL_LB_NM = 'name';
	public const COL_STG_NM = 'name';
	public const COL_PPL_NM = 'name';
	public const COL_STG = 'stage';
	public const COL_S_DT = 'start_date';
	public const COL_E_DT = 'end_date';
	public const COL_PLN_ST = 'planned_start';
	public const COL_D_DATE = 'due_date';
	public const COL_E_HRS = 'estimated_hrs';
	public const COL_ACT_HRS = 'actual_hrs';
	public const COL_LAST_ACT_AT = 'last_activity_at';
	public const COL_PRT = 'priority';
	public const COL_IS_CP = 'is_complete';
	public const COL_IS_FV = 'is_favorite';
	public const COL_M_AT = 'marked_at';
	public const COL_PGR = 'progress';
	public const COL_PR_CL = 'priority_color';
	public const COL_IMG            = 'project_image';
	public const COL_BUDGET         = 'budget';
	public const COL_CLIENT_ID      = 'client_id';
	public const COL_CLIENT_NAME    = 'client_name';
	public const COL_STAGE_ID       = 'project_stage_id';
	public const COL_DESCRIPTION    = 'description';
	public const COL_STATUS         = 'status';
	public const COL_PASSWORD       = 'password';
	public const COL_COPYLINK       = 'copylinksetting';
	public const COL_TAGS           = 'tags';
	public const COL_CTC_ID = 'contract_id';
	public const COL_JRN_ID = 'journal_id';
	public const COL_RVS_DT = 'reversal_date';
	public const COL_CN = 'contract_number';
	public const COL_CDESC = 'contract_description';
	public const COL_ARNW = 'auto_renew';
	public const COL_OBG_NAME = 'obligee_name';
	public const COL_OBL_NAME = 'obligor_name';
	public const COL_OBG_IDF = 'obligee_identifier';
	public const COL_OBL_IDF = 'obligor_identifier';
	public const COL_OBG_ADDR = 'obligee_address';
	public const COL_OBL_ADDR = 'obligor_address';
	public const COL_OBG_CTC = 'obligee_contact';
	public const COL_OBL_CTC = 'obligor_contact';
	public const COL_WT_NM = 'witness_one_name';
	public const COL_WT2_NM = 'witness_two_name';
	public const COL_WT_IDF = 'witness_one_identifier';
	public const COL_WT2_IDF = 'witness_two_identifier';
	public const COL_WT_SIG = 'witness_one_signature';
	public const COL_WT2_SIG = 'witness_two_signature';
	public const COL_WT_SIGN_AT = 'witness_one_signed_at';
	public const COL_WT2_SIGN_AT = 'witness_two_signed_at';
	public const COL_CL_SIG = 'client_signature';
	public const COL_CO_SIG = 'company_signature';
	public const COL_CL_SIGN_AT = 'client_signed_at';
	public const COL_CO_SIGN_AT = 'company_signed_at';
	public const COL_F_PATH = 'file_path';
	public const COL_ATC_PATHS = 'attachment_paths';
	public const COL_APV_BY = 'approved_by';
	public const COL_APV_AT = 'approved_at';
	public const COL_SBM_BY = 'submitted_by';
	public const COL_SBM_AT = 'submitted_at';
	public const COL_REJ_BY = 'rejected_by';
	public const COL_REJ_AT = 'rejected_at';
	public const COL_M_METRIC = 'main_metric';
	public const COL_CRT = 'is_critical';
	public const COL_CNV = 'is_converted';
	public const COL_EXT_DY = 'extensible_days';
	public const COL_HLT_RL = 'is_health_related';
	public const COL_SL_MIN_DD_PCT = 'salary_minimum_deduction_percent';
	public const COL_SL_MAX_DD_PCT = 'salary_maximum_deduction_percent';
	public const COL_APL_ON = 'applied_on';
	public const COL_TT_LV_DY = 'total_leave_days';
	public const COL_LV_RS = 'leave_reason';
	public const COL_MIN_DR = 'minimum_duration';
	public const COL_MAX_DR = 'maximum_duration';
	public const COL_EXP_DR = 'expected_duration';
	public const COL_EST_CC = 'estimated_chance_of_continuation';
	public const COL_STG_ID = 'stage_id';
	public const COL_LD_ID = 'lead_id';
	public const COL_ATC_FRULES = 'attachment_filter_rules';
	public const COL_IS_FUP = 'is_follow_up';
	public const COL_GRP_ID = 'group_id';
	public const COL_IS_DSP = 'is_display';
	public const COL_GL_TP = 'goal_type';
	public const COL_TRG_ACHV = 'target_achievement';
	public const COL_CST_EXP = 'customer_experience';
	public const COL_APR_DT = 'appraisal_date';
	public const COL_AOM_ID = 'agent_or_manager_id';
	public const COL_CMP_AT = 'completed_at';
	public const COL_ASG_BY = 'assigned_by';
	public const COL_ASG_AT = 'assigned_at';
	public const COL_RDC_SHFT_BY = 'reduced_shift_by';
	public const COL_TAG_ID = 'tag_id';
	public const COL_IS_BLB = 'is_billable';
	public const COL_BLB_HRS = 'billable_hours';
	public const COL_HRS_WTT_TIMER = 'hours_without_timer';
	public const COL_HR_PRC = 'hourly_price';
	public const COL_INV_BY = 'invited_by';
	public const COL_INV_AT = 'invited_at';
	public const COL_INV_STT = 'invite_status';
	public const COL_INV_URL = 'invite_url';
	public const COL_INV_CD = 'invite_code';
	public const COL_JND_AT = 'joined_at';
	public const COL_ACC_AT = 'accepted_at';
	public const COL_ACC_BY = 'accepted_by';
	public const COL_LFT_AT = 'left_at';
	public const COL_RMV_BY = 'removed_by';
	public const COL_IS_TMP = 'is_temporary';
	public const COL_EXP_AT = 'expires_at';
	public const COL_LST_EDT_AT = 'last_edited_at';
	public const COL_CAN_WRT_OWN = 'can_write_own_files';
	public const COL_CAN_WRT_OTH = 'can_write_others_files';
	public const COL_CAN_RD_OTH = 'can_read_others_files';
	public const COL_IS_PRJ_LD = 'is_project_leader';
	public const COL_ALW_EML_NTF = 'allow_email_notifications';
	public const COL_ALW_PSH_NTF = 'allow_push_notifications';
	public const COL_ALW_MNT_NTF = 'allow_mention_notifications';
	public const COL_ALW_STT_UPD_NTF = 'allow_status_update_notifications';
	public const COL_TTL_HRS = 'total_hours';
	public const COL_SHFT_TP = 'shift_type';
	public const COL_ACP_SHFT = 'accepted_shifts';
	public const COL_PRS_TP = 'presence_type';
	public const COL_ACP_PRS = 'accepted_presences';
	public const COL_CTC_TP = 'contract_type';
	public const COL_ACP_CTC_TP = 'accepted_contract_types';
	public const COL_ACP_LVLS = 'accepted_levels';
	public const COL_TRK_ID = 'track_id';
	public const COL_IMG_PATH = 'image_path';

	public const STT_INP_K					 = 'in_progress';
	public const STT_ONH_K					 = 'on_hold';
	public const STT_CPT_K					 = 'complete';
	public const STT_CCL_K					 = 'canceled';
	public const STT_DEF_K					 = self::STT_INP_K;
	public const STT_INF						 = 'info';
	public const STT_WRN						 = 'warning';
	public const STT_SCS						 = 'success';
	public const STT_DGR						 = 'danger';
	public const STT_DEF_CL					 = self::STT_INF;
	public const VST_PPS = 'purpose_of_visit';
	public const VST_PLC = 'place_of_visit';
	public static array $projectStatus = [
		self::STT_INP_K => 'In Progress',
		self::STT_ONH_K     => 'On Hold',
		self::STT_CPT_K    => 'Complete',
		self::STT_CCL_K    => 'Canceled',
	];
	public static array $statusColor = [
		self::STT_INP_K => self::STT_INF,
		self::STT_ONH_K     => self::STT_WRN,
		self::STT_CPT_K    => self::STT_SCS,
		self::STT_CCL_K    => self::STT_DGR,
	];
}
