<?php

namespace App\Config\Constants;

class SettingsConstants
{
	public const ENTITY = 'settings';
	public const WARN_TRACE = 'warning_trace';
	public const ERR_TRACE = 'error_trace';
	public const CRT_TRACE = 'critical_trace';
	public const MD_LO = 'mode_layout';
	public const CLR = 'color';
	public const CLR_STG = 'color_settings';
	public const THM_CLR = 'theme_color';
	public const THM_CLR_DEF = 'theme-3';
	public const CST_DRK = 'cust_darklayout';
	public const CST_BG = 'cust_theme_bg';
	public const MT_TTL_K = 'meta_title';
	public const MT_DSC_K = 'meta_desc';
	public const MT_DESC_LONG = 'meta_description';
	public const MT_IMG_K = 'meta_image';
	public const MT_LOGO = 'meta_logo';
	public const LOGO = 'logo';
	public const SC_LOGO = 'secondary_logo';
	public const FAV_ICN = 'favicon';
	public const CPN_LG = 'company_logo';
	public const CPN_LG_LT = 'company_logo_light';
	public const CPN_LG_LT_DEF = 'logo-light.webp';
	public const CPN_LG_DK = 'company_logo_dark';
	public const CPN_LG_DK_DEF = 'logo-dark.webp';
	public const CPN_FAVICON_K = "company_favicon";
	public const CPN_FAVICON_DEF = "favicon.ico";
	public const CPN_CFG = 'company_config';
	public const G_RCPT_RES = 'g-recaptcha-response';
	public const G_RCPT_SC = 'google_recaptcha_secret';
	public const G_RCPT_K = 'google_recaptcha_key';
	public const RCPT_MDL = 'recaptcha_module';
	public const ENB_SGU = 'enable_signup';
	public const DSB_LNG = 'disable_lang';
	public const RTL = 'site_rtl';
	public const LCL = 'locale';
	public const DEF_LNG = 'default_language';
	public const CK_STG = 'cookie_settings';
	public const FT_TXT = 'footer_text';
	public const STR_STT = 'storage_setting';
	public const LC = 'local';
	public const LC_ST = 'local_storage';
	public const LC_ST_VL = self::LC_ST . '_validation';
	public const LC_ST_M_UP = self::LC_ST . '_max_upload_size';
	public const WSB = 'wasabi';
	public const WSB_K = self::WSB . '_key';
	public const WSB_SC = self::WSB . '_secret';
	public const WSB_RG = self::WSB . '_region';
	public const WSB_BK = self::WSB . '_bucket';
	public const WSB_URL = self::WSB . '_url';
	public const WSB_RT = self::WSB . '_root';
	public const WSB_M_UP = self::WSB . '_max_upload_size';
	public const WSB_STG_VL = self::WSB . '_storage_validation';
	public const S3 = 's3';
	public const S3_K = self::S3 . '_key';
	public const S3_SC = self::S3 . '_secret';
	public const S3_RG = self::S3 . '_region';
	public const S3_BK = self::S3 . '_bucket';
	public const S3_URL = self::S3 . '_url';
	public const S3_RT = self::S3 . '_root';
	public const S3_M_UP = self::S3 . '_max_upload_size';
	public const S3_STG_VL = self::S3 . '_storage_validation';
	public const S3_EP = self::S3 . '_endpoint';
	public const MAX_U_SIZE_DEF = "2048000";
	public const MAX_SL_LIMIT_MB = 1024;
	public const FMTS_UP_DEF = 'jpg,jpeg,png,xlsx,xls,csv,pdf';
	public const CLR_CD = [
		1 => 'event-warning',
		2 => 'event-secondary',
		3 => 'event-info',
		4 => 'event-warning',
		5 => 'event-danger',
		6 => 'event-dark',
		7 => 'event-black',
		8 => 'event-info',
		9 => 'event-dark',
		10 => 'event-success',
		11 => 'event-warning',
	];
	public const DFT_SETTINGS =  [
		"lang" => DatabaseConstants::DEFAULT_LANG,
		PlansConstants::COL_SL => self::MAX_SL_LIMIT_MB,
		"site_currency" => "BRL",
		"site_currency_symbol" => "R$",
		"site_currency_symbol_position" => "pre",
		"site_date_format" => "M j, Y",
		"site_time_format" => "g:i A",
		"timezone" => '',
		"company_name" => "",
		"company_address" => "",
		"company_city" => "",
		"company_state" => "",
		"company_zipcode" => "",
		"company_country" => "",
		"company_telephone" => "",
		"invoice_prefix" => "#INVO",
		"journal_prefix" => "#JUR",
		"invoice_color" => "ffffff",
		"proposal_prefix" => "#PROP",
		"proposal_color" => "ffffff",
		"bill_prefix" => "#BILL",
		"expense_prefix" => "#EXP",
		"bill_color" => "ffffff",
		"customer_prefix" => "#CUST",
		"vendor_prefix" => "#VEND",
		"footer_title" => "",
		"footer_notes" => "",
		BillsConstants::COL_INV_TMP => "template1",
		BillsConstants::COL_BIL_TMP => "template1",
		BillsConstants::COL_PPS_TMP => "template1",
		BillsConstants::COL_PRC_TMP => "template1",
		BillsConstants::COL_POS_TMP => "template1",
		"registration_number" => "",
		"vat_number" => "",
		"default_language" => "en",
		"enable_stripe" => "",
		"enable_paypal" => "",
		"paypal_mode" => "",
		"paypal_client_id" => "",
		"paypal_secret_key" => "",
		"stripe_key" => "",
		"stripe_secret" => "",
		"decimal_number" => "2",
		"tax_type" => "",
		"shipping_display" => "on",
		"display_landing_page" => "on",
		"employee_prefix" => "#EMP00",
		'leave_status' => '1',
		"bug_prefix" => "#ISSUE",
		'title_text' => '',
		self::FT_TXT => '',
		"company_start_time" => "09:00",
		"company_end_time" => "18:00",
		'gdpr_cookie' => 'off',
		"interval_time" => "",
		"zoom_apikey" => "",
		"zoom_apisecret" => "",
		"slack_webhook" => "",
		"telegram_accestoken" => "",
		"telegram_chatid" => "",
		self::ENB_SGU => "on",
		"email_verification" => "on",
		'cookie_text' => 'We use cookies to ensure that we give you the best experience on our website. If you continue to use this site we will assume that you are happy with it.
		',
		self::CPN_LG_LT => self::CPN_LG_LT_DEF,
		self::CPN_LG_DK => self::CPN_LG_DK_DEF,
		self::CPN_FAVICON_K => self::CPN_FAVICON_DEF,
		self::CST_BG => "on",
		self::CST_DRK => "off",
		self::CLR => "",
		self::RTL => "off",
		"purchase_prefix" => "#PUR",
		"purchase_color" => "ffffff",
		"pos_color" => "ffffff",
		"pos_prefix" => "#POS",

		self::STR_STT => self::LC,
		self::LC_ST_VL => self::FMTS_UP_DEF,
		self::LC_ST_M_UP => self::MAX_U_SIZE_DEF,
		self::S3_K => "",
		self::S3_SC => "",
		self::S3_RG => "",
		self::S3_BK => "",
		self::S3_URL    => "",
		self::S3_EP => "",
		self::S3_M_UP => '',
		self::S3_STG_VL => "",
		self::WSB_K => "",
		self::WSB_SC => "",
		self::WSB_RG => "",
		self::WSB_BK => "",
		self::WSB_URL => "",
		self::WSB_RT => "",
		self::WSB_M_UP => "",
		self::WSB_STG_VL => "",

		"purchase_logo" => "",
		"proposal_logo" => "",
		"invoice_logo" => "",
		"bill_logo" => "",
		"pos_logo" => "",
		"contract_prefix" => "#CON",

		"barcode_type" => "code128",
		"barcode_format" => "css",

		'new_user' => '1',
		'new_client' => '1',
		'new_support_ticket' => '1',
		'lead_assigned' => '1',
		'deal_assigned' => '1',
		'new_award' => '1',
		'customer_invoice_sent' => '1',
		'new_invoice_payment' => '1',
		'new_payment_reminder' => '1',
		'new_bill_payment' => '1',
		'bill_resent' => '1',
		'proposal_sent' => '1',
		'complaint_resent' => '1',
		'leave_action_sent' => '1',
		'payslip_sent' => '1',
		'promotion_sent' => '1',
		'resignation_sent' => '1',
		'termination_sent' => '1',
		'transfer_sent' => '1',
		'trip_sent' => '1',
		'vendor_bill_sent' => '1',
		'warning_sent' => '1',
		'new_contract' => '1',
		'vat_gst_number_switch' => 'off',
		'google_calendar_enable' => 'off',
		'google_calendar_json_file' => '',

		self::MT_TTL_K => 'ERP Test',
		self::MT_DSC_K => 'Develop your app!',
		self::MT_IMG_K => '',

		'enable_cookie' => 'on',
		'necessary_cookies' => 'on',
		'cookie_logging' => 'on',
		'cookie_title' => 'We use cookies!',
		'cookie_description' => 'Hi, this website uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it',
		'strictly_cookie_title' => 'Strictly necessary cookies',
		'strictly_cookie_description' => 'These cookies are essential for the proper functioning of my website. Without these cookies, the website would not work properly',
		'more_information_description' => 'For any queries in relation to our policy on cookies and your choices, please contact us',
		'contactus_url' => '#',

		'twilio_sid' => '',
		'twilio_token' => '',
		'twilio_from' => '',
		'twilio_from' => '',
		'chat_gpt_key' => '',
		"ip_restrict" => "off",

		'mail_driver' => '',
		'mail_host' => '',
		'mail_port' => '',
		'mail_username' => '',
		'mail_password' => '',
		'mail_encryption' => '',
		'mail_from_address' => '',
		'mail_from_name' => '',

		self::RCPT_MDL => 'off',
		self::G_RCPT_K => '',
		self::G_RCPT_SC => '',

		'pusher_app_id' => '',
		'pusher_app_key' => '',
		'pusher_app_secret' => '',
		'pusher_app_cluster' => '',

	];
	public const DFT_SETTINGS_IDF = [
		"site_currency" => "USD",
		"site_currency_symbol" => "$",
		"site_currency_symbol_position" => "pre",
		"site_date_format" => "M j, Y",
		"site_time_format" => "g:i A",
		"company_name" => "",
		"company_address" => "",
		"company_city" => "",
		"company_state" => "",
		"company_zipcode" => "",
		"company_country" => "",
		"company_telephone" => "",
		"invoice_prefix" => "#INVO",
		"invoice_color" => "ffffff",
		"proposal_prefix" => "#PROP",
		"proposal_color" => "ffffff",
		"bill_prefix" => "#BILL",
		"expense_prefix" => "#EXP",
		"bill_color" => "ffffff",
		"customer_prefix" => "#CUST",
		"vendor_prefix" => "#VEND",
		"footer_title" => "",
		"footer_notes" => "",
		BillsConstants::COL_INV_TMP => "template1",
		BillsConstants::COL_BIL_TMP => "template1",
		BillsConstants::COL_PPS_TMP => "template1",
		BillsConstants::COL_PRC_TMP => "template1",
		BillsConstants::COL_POS_TMP => "template1",
		"registration_number" => "",
		"vat_number" => "",
		"default_language" => "en",
		"enable_stripe" => "",
		"enable_paypal" => "",
		"paypal_mode" => "",
		"paypal_client_id" => "",
		"paypal_secret_key" => "",
		"stripe_key" => "",
		"stripe_secret" => "",
		"decimal_number" => "2",
		"tax_type" => "",
		"shipping_display" => "on",
		"journal_prefix" => "#JUR",
		"display_landing_page" => "on",
		"employee_prefix" => "#EMP00",
		'leave_status' => '1',
		"bug_prefix" => "#ISSUE",
		'title_text' => '',
		self::FT_TXT => '',
		"company_start_time" => "09:00",
		"company_end_time" => "18:00",
		'gdpr_cookie' => 'off',
		"interval_time" => "",
		"zoom_apikey" => "",
		"zoom_apisecret" => "",
		"slack_webhook" => "",
		"telegram_accestoken" => "",
		"telegram_chatid" => "",
		self::RCPT_MDL => 'off',
		self::G_RCPT_K => '',
		self::G_RCPT_SC => '',
		self::ENB_SGU => "on",
		"email_verification" => "on",
		'cookie_text' => 'We use cookies to ensure that we give you the best experience on our website. If you continue to use this site we will assume that you are happy with it.
		',
		self::CPN_LG_LT => self::CPN_LG_LT_DEF,
		self::CPN_LG_DK => self::CPN_LG_DK_DEF,
		self::CPN_FAVICON_K => self::CPN_FAVICON_DEF,
		self::CST_BG => "on",
		self::CST_DRK => "off",
		self::CLR => "",
		self::RTL => "off",
		"purchase_prefix" => "#PUR",
		"purchase_color" => "ffffff",
		"proposal_logo" => "",
		"purchase_logo" => "",
		"invoice_logo" => "",
		"bill_logo" => "",
		"pos_logo" => "",
		"pos_color" => "ffffff",

		self::STR_STT => self::LC,
		self::LC_ST_VL => self::FMTS_UP_DEF,
		self::LC_ST_M_UP => self::MAX_U_SIZE_DEF,
		self::S3_K => "",
		self::S3_SC => "",
		self::S3_RG => "",
		self::S3_BK => "",
		self::S3_URL    => "",
		self::S3_EP => "",
		self::S3_M_UP => '',
		self::S3_STG_VL => "",
		self::WSB_K => "",
		self::WSB_SC => "",
		self::WSB_RG => "",
		self::WSB_BK => "",
		self::WSB_URL => "",
		self::WSB_RT => "",
		self::WSB_M_UP => "",
		self::WSB_STG_VL => "",

		"barcode_type" => "code128",
		"barcode_format" => "css",

		'new_user' => '1',
		'new_client' => '1',
		'new_support_ticket' => '1',
		'lead_assigned' => '1',
		'deal_assigned' => '1',
		'new_award' => '1',
		'customer_invoice_sent' => '1',
		'new_invoice_payment' => '1',
		'new_payment_reminder' => '1',
		'new_bill_payment' => '1',
		'bill_resent' => '1',
		'proposal_sent' => '1',
		'complaint_resent' => '1',
		'leave_action_sent' => '1',
		'payslip_sent' => '1',
		'promotion_sent' => '1',
		'resignation_sent' => '1',
		'termination_sent' => '1',
		'transfer_sent' => '1',
		'trip_sent' => '1',
		'vendor_bill_sent' => '1',
		'warning_sent' => '1',
		'new_contract' => '1',

		'vat_gst_number_switch' => 'off',
		'google_calendar_enable' => 'on',
		'google_calendar_json_file' => '',

		self::MT_IMG_K => '',
		self::MT_DSC_K => '',
		self::MT_IMG_K => '',

		'enable_cookie' => 'on',
		'necessary_cookies' => 'on',
		'cookie_logging' => 'on',
		'cookie_title' => 'We use cookies!',
		'cookie_description' => 'Hi, this website uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it',
		'strictly_cookie_title' => 'Strictly necessary cookies',
		'strictly_cookie_description' => 'These cookies are essential for the proper functioning of my website. Without these cookies, the website would not work properly',
		'more_information_description' => 'For any queries in relation to our policy on cookies and your choices, please contact us',
		'contactus_url' => '#',

		'twilio_sid' => '',
		'twilio_token' => '',
		'twilio_from' => '',
		'chat_gpt_key' => '',
		"ip_restrict" => "off",
		"timezone" => '',

		'pusher_app_id' => '',
		'pusher_app_key' => '',
		'pusher_app_secret' => '',
		'pusher_app_cluster' => '',

	];
}
