<?php

namespace App\Config\Constants;

class UsersConstants
{
	public const COL_NM = 'name';
	public const COL_EM = 'email';
	public const COL_EM_KEY = 'email_key';
	public const COL_PW = 'password';
	public const COL_EM_V_AT = 'email_verified_at';
	public const COL_TP = 'type';
	public const COL_C_AT = 'created_at';
	public const COL_U_AT = 'updated_at';
	public const COL_SL = 'storage_limit';
	public const COL_AV = 'avatar';
	public const COL_MC = 'messenger_color';
	public const COL_MSG_CL = self::COL_MC;
	public const COL_LG = 'lang';
	public const COL_DPL = 'default_pipeline';
	public const COL_A_ST = 'active_status';
	public const COL_D_ST = 'delete_status';
	public const COL_DEL_STT = self::COL_D_ST;
	public const COL_MD = 'mode';
	public const COL_DM = 'dark_mode';
	public const COL_IA = 'is_active';
	public const COL_IS_RD = 'is_ready';
	public const COL_IB = 'is_banned';
	public const COL_LLA = 'last_login_at';
	public const COL_PL = 'plan';
	public const COL_PED = self::COL_PL . '_expire_date';
	public const COL_RP = 'requested_' . self::COL_PL;
	public const COL_USER_ID = 'user_id';
	public const COL_U_TP = 'user_type';
	public const COL_EMP_ID = 'employee_id';
	public const COL_PLAN_ID = 'plan_id';
	public const COL_PLAN_NM = 'plan_name';
	public const COL_BRC_ID = 'branch_id';
	public const COL_DEP_ID = 'department_id';
	public const COL_DSG_ID = 'designation_id';
	public const COL_TAX_ID = 'tax_payer_id';
	public const COL_DSG_NM = 'name';
	public const COL_SLR = 'salary';
	public const COL_SLR_TP = 'salary_type';
	public const COL_RT = 'remember_token';
	public const TP_CT = 'contact';
	public const COL_TEL = 'phone';
	public const COL_ADR = 'address';
	public const COL_IU = 'is_user';
	public const COL_ACC_HD = 'account_holder_name';
	public const COL_ACC_NM = 'account_number';
	public const COL_BANK_NM = 'bank_name';
	public const COL_BANK_IC = 'bank_identifier_code';
	public const COL_AWD_TP = 'award_type';
	public const COL_TERMINATION_TP = 'termination_type';
	public const COL_TERMINATION_DT = 'termination_date';
	public const COL_TERMINATION_NDT = 'notice_date';
	public const COL_RESIGNATION_NDT = self::COL_TERMINATION_NDT;
	public const COL_RESIGNATION_DT = 'resignation_date';
	public const COL_PRMT_DT = 'promotion_date';
	public const COL_PRMT_TL = 'promotion_title';
	public const COL_TRF_DT = 'transfer_date';
	public const COL_NDAYS = 'number_of_days';
	public const COL_IS_SYS = 'is_system_account';
	public const COL_PD_UPD = 'has_pending_updates';
	public const COL_RSP_ID = 'responsible_id';
	public const COL_RSP_NM = 'responsible_name';
	public const COL_RSP_TEL = 'responsible_phone';
	public const COL_RSP_EM = 'responsible_email';
	public const COL_RSP_ADDR = 'responsible_address';
	public const COL_AVG_RT = 'average_rating';
	public const COL_VD_ID = 'vendor_id';
	public const COL_ENT_TP = 'entity_type';
	public const COL_ENT_CD = 'entity_code';
}
