<?php

namespace App\Enums;

use App\Config\Constants\DatabaseConstants;

enum GoalType: string
{
	// Original & Core Financial Goals
	case Invoice              = 'invoice';
	case Bill                 = 'bill';
	case Revenue              = 'revenue';
	case Payment              = 'payment';

		// Expanded Financial Goals
	case GeneralLedgerAccuracy = 'general_ledger_accuracy';
	case AccountsReceivableDays = 'accounts_receivable_days';
	case AccountsPayableEfficiency = 'accounts_payable_efficiency';
	case CostReduction        = 'cost_reduction';
	case BudgetAdherence      = 'budget_adherence';
	case CashFlowTarget       = 'cash_flow_target';
	case AssetUtilization     = 'asset_utilization';
	case AuditReadiness       = 'audit_readiness';
	case TaxCompliance        = 'tax_compliance';
	case FinancialCloseTime   = 'financial_close_time';
	case ExpenseRatio         = 'expense_ratio';

		// Sales & Marketing Goals
	case SalesQuota           = 'sales_quota';
	case LeadConversion       = 'lead_conversion';
	case CustomerAcquisitionCost = 'customer_acquisition_cost';
	case MarketShareGrowth    = 'market_share_growth';
	case CustomerLifetimeValue = 'customer_lifetime_value';
	case CampaignROI          = 'campaign_roi';
	case DealSize             = 'deal_size';
	case SalesCycleLength     = 'sales_cycle_length';
	case PipelineValue        = 'pipeline_value';

		// Project Management Goals
	case MilestoneCompletion  = 'milestone_completion';
	case ProjectOnTime        = 'project_on_time';
	case ProjectOnBudget      = 'project_on_budget';
	case DeliverableQuality   = 'deliverable_quality';
	case ScopeAdherence       = 'scope_adherence';
	case StakeholderSatisfaction = 'stakeholder_satisfaction';
	case ResourceUtilization  = 'resource_utilization';
	case RiskMitigation       = 'risk_mitigation';
	case TeamVelocity         = 'team_velocity';

		// Human Resources Goals
	case HeadcountManagement  = 'headcount_management';
	case EmployeeRetention    = 'employee_retention';
	case TrainingCompletion   = 'training_completion';
	case WorkforceCostOptimization = 'workforce_cost_optimization';
	case SuccessionPlanning   = 'succession_planning';
	case PerformanceReviewCompletion = 'performance_review_completion';
	case EmployeeEngagement   = 'employee_engagement';
	case TimeToHire           = 'time_to_hire';
	case DiversityRatio       = 'diversity_ratio';

		// IT & Operations Goals
	case SystemUptime         = 'system_uptime';
	case HelpDeskResolutionTime = 'help_desk_resolution_time';
	case ProjectDeployment    = 'project_deployment';
	case SecurityIncidentCount = 'security_incident_count';
	case DataBackupSuccess    = 'data_backup_success';
	case SoftwareAssetOptimization = 'software_asset_optimization';
	case NetworkPerformance   = 'network_performance';
	case IncidentResponseTime = 'incident_response_time';
	case InfrastructureCostPerUser = 'infrastructure_cost_per_user';

		// Administration & Strategic Goals
	case OperationalEfficiency = 'operational_efficiency';
	case StrategicInitiative  = 'strategic_initiative';
	case PolicyCompliance     = 'policy_compliance';
	case FacilityManagement   = 'facility_management';
	case SustainabilityTarget = 'sustainability_target';
	case VendorManagement     = 'vendor_management';
	case DocumentControl      = 'document_control';
	case BusinessContinuity   = 'business_continuity';

	public static function normalize(string|null|self $value = null): self
	{
		if ($value instanceof self)
			return $value;
		if ($value === null)
			return self::Revenue; // Default to a common business goal

		$normalizedValue = preg_replace('/[^a-z0-9_]/', '', strtolower(trim($value ?? '')));
		return match ($normalizedValue) {
			// Original & Core Financial
			'invoice' => self::Invoice,
			'bill' => self::Bill,
			'revenue', 'salesrevenue' => self::Revenue,
			'payment', 'paymentcollection' => self::Payment,

			// Expanded Financial
			'generalledgeraccuracy', 'glaccuracy' => self::GeneralLedgerAccuracy,
			'accountsreceivabledays', 'ardays', 'dso' => self::AccountsReceivableDays,
			'accountspayableefficiency', 'apefficiency', 'dpo' => self::AccountsPayableEfficiency,
			'costreduction', 'costsavings' => self::CostReduction,
			'budgetadherence', 'budgetcompliance' => self::BudgetAdherence,
			'cashflowtarget', 'cashflow' => self::CashFlowTarget,
			'assetutilization', 'assetusage' => self::AssetUtilization,
			'auditreadiness', 'auditcompliance' => self::AuditReadiness,
			'taxcompliance', 'taxreporting' => self::TaxCompliance,
			'financialclosetime', 'closetime' => self::FinancialCloseTime,
			'expenseratio', 'opexratio' => self::ExpenseRatio,

			// Sales & Marketing
			'salesquota', 'quotatarget' => self::SalesQuota,
			'leadconversion', 'conversionrate' => self::LeadConversion,
			'customeracquisitioncost', 'cac' => self::CustomerAcquisitionCost,
			'marketsharegrowth', 'marketshare' => self::MarketShareGrowth,
			'customerlifetimevalue', 'clv', 'ltv' => self::CustomerLifetimeValue,
			'campaignroi', 'marketingroi' => self::CampaignROI,
			'dealsize', 'averagedealsize' => self::DealSize,
			'salescyclelength', 'salescycle' => self::SalesCycleLength,
			'pipelinevalue', 'salespipeline' => self::PipelineValue,

			// Project Management
			'milestonecompletion', 'milestonetarget' => self::MilestoneCompletion,
			'projectontime', 'timelydelivery' => self::ProjectOnTime,
			'projectonbudget', 'budgetcomplianceproject' => self::ProjectOnBudget,
			'deliverablequality', 'qualitytarget' => self::DeliverableQuality,
			'scopeadherence', 'scopecompliance' => self::ScopeAdherence,
			'stakeholdersatisfaction', 'stakeholderfeedback' => self::StakeholderSatisfaction,
			'resourceutilization', 'resourceefficiency' => self::ResourceUtilization,
			'riskmitigation', 'riskmanagement' => self::RiskMitigation,
			'teamvelocity', 'velocity' => self::TeamVelocity,

			// Human Resources
			'headcountmanagement', 'headcountplanning' => self::HeadcountManagement,
			'employeeretention', 'retentionrate' => self::EmployeeRetention,
			'trainingcompletion', 'trainingrate' => self::TrainingCompletion,
			'workforcecostoptimization', 'laborcostoptimization' => self::WorkforceCostOptimization,
			'successionplanning', 'successionreadiness' => self::SuccessionPlanning,
			'performancereviewcompletion', 'reviewcompletion' => self::PerformanceReviewCompletion,
			'employeeengagement', 'engagementscore' => self::EmployeeEngagement,
			'timetohire', 'hiringtime' => self::TimeToHire,
			'diversityratio', 'diversitytarget' => self::DiversityRatio,

			// IT & Operations
			'systemuptime', 'uptime' => self::SystemUptime,
			'helpdeskresolutiontime', 'resolutiontime' => self::HelpDeskResolutionTime,
			'projectdeployment', 'deploymentsuccess' => self::ProjectDeployment,
			'securityincidentcount', 'securityincidents' => self::SecurityIncidentCount,
			'databackupsuccess', 'backupsuccessrate' => self::DataBackupSuccess,
			'softwareassetoptimization', 'softwarelicenseoptimization' => self::SoftwareAssetOptimization,
			'networkperformance', 'networklatency' => self::NetworkPerformance,
			'incidentresponsetime', 'responsetime' => self::IncidentResponseTime,
			'infrastructurecostperuser', 'itcostperuser' => self::InfrastructureCostPerUser,

			// Administration & Strategic
			'operationalefficiency', 'efficiencytarget' => self::OperationalEfficiency,
			'strategicinitiative', 'strategicgoal' => self::StrategicInitiative,
			'policycompliance', 'complianceadherence' => self::PolicyCompliance,
			'facilitymanagement', 'facilitycosts' => self::FacilityManagement,
			'sustainabilitytarget', 'sustainabilitygoal' => self::SustainabilityTarget,
			'vendormanagement', 'vendorperformance' => self::VendorManagement,
			'documentcontrol', 'documentmanagement' => self::DocumentControl,
			'businesscontinuity', 'continuityplanning' => self::BusinessContinuity,

			default => self::Revenue,
		};
	}

	public static function values(): array
	{
		return array_map(fn($case) => $case->value, self::cases());
	}

	public static function labels($lang = DatabaseConstants::DEFAULT_LANG): array
	{
		$lang = preg_replace('/_/', '-', strtolower(trim($lang ?? '')));
		return match ($lang) {
			'pt-br', 'pt' => self::labelsPtBr(),
			'es', 'es-es' => self::labelsEs(),
			'ar', 'ar-sa' => self::labelsAr(),
			'da', 'da-dk' => self::labelsDa(),
			'de', 'de-de' => self::labelsDe(),
			'fr', 'fr-fr' => self::labelsFr(),
			'he', 'he-il' => self::labelsHe(),
			'it', 'it-it' => self::labelsIt(),
			'ja', 'ja-jp' => self::labelsJa(),
			'nl', 'nl-nl' => self::labelsNl(),
			'pl', 'pl-pl' => self::labelsPl(),
			'ru', 'ru-ru' => self::labelsRu(),
			'tr', 'tr-tr' => self::labelsTr(),
			'zh', 'zh-cn' => self::labelsZh(),
			default => self::labelsEn(),
		};
	}

	public static function labelsPtBr(): array
	{
		return [
			self::Invoice->value => 'Fatura',
			self::Bill->value => 'Conta',
			self::Revenue->value => 'Receita',
			self::Payment->value => 'Pagamento',
			self::GeneralLedgerAccuracy->value => 'Precisão do Razão Geral',
			self::AccountsReceivableDays->value => 'Dias de Contas a Receber',
			self::AccountsPayableEfficiency->value => 'Eficiência de Contas a Pagar',
			self::CostReduction->value => 'Redução de Custos',
			self::BudgetAdherence->value => 'Aderência Orçamentária',
			self::CashFlowTarget->value => 'Meta de Fluxo de Caixa',
			self::AssetUtilization->value => 'Utilização de Ativos',
			self::AuditReadiness->value => 'Preparação para Auditoria',
			self::TaxCompliance->value => 'Conformidade Fiscal',
			self::FinancialCloseTime->value => 'Tempo de Fechamento Financeiro',
			self::ExpenseRatio->value => 'Rácio de Despesas',
			self::SalesQuota->value => 'Cota de Vendas',
			self::LeadConversion->value => 'Conversão de Leads',
			self::CustomerAcquisitionCost->value => 'Custo de Aquisição de Cliente',
			self::MarketShareGrowth->value => 'Crescimento de Participação de Mercado',
			self::CustomerLifetimeValue->value => 'Valor do Cliente ao Longo da Vida',
			self::CampaignROI->value => 'ROI de Campanha',
			self::DealSize->value => 'Tamanho do Negócio',
			self::SalesCycleLength->value => 'Duração do Ciclo de Vendas',
			self::PipelineValue->value => 'Valor do Pipeline',
			self::MilestoneCompletion->value => 'Conclusão de Marco',
			self::ProjectOnTime->value => 'Projeto no Prazo',
			self::ProjectOnBudget->value => 'Projeto no Orçamento',
			self::DeliverableQuality->value => 'Qualidade da Entrega',
			self::ScopeAdherence->value => 'Aderência ao Escopo',
			self::StakeholderSatisfaction->value => 'Satisfação das Partes Interessadas',
			self::ResourceUtilization->value => 'Utilização de Recursos',
			self::RiskMitigation->value => 'Mitigação de Riscos',
			self::TeamVelocity->value => 'Velocidade da Equipe',
			self::HeadcountManagement->value => 'Gestão de Efetivos',
			self::EmployeeRetention->value => 'Retenção de Funcionários',
			self::TrainingCompletion->value => 'Conclusão de Treinamento',
			self::WorkforceCostOptimization->value => 'Otimização de Custos da Força de Trabalho',
			self::SuccessionPlanning->value => 'Planeamento de Sucessão',
			self::PerformanceReviewCompletion->value => 'Conclusão de Avaliação de Desempenho',
			self::EmployeeEngagement->value => 'Engajamento dos Funcionários',
			self::TimeToHire->value => 'Tempo para Contratar',
			self::DiversityRatio->value => 'Taxa de Diversidade',
			self::SystemUptime->value => 'Tempo de Atividade do Sistema',
			self::HelpDeskResolutionTime->value => 'Tempo de Resolução do Help Desk',
			self::ProjectDeployment->value => 'Implantação de Projeto',
			self::SecurityIncidentCount->value => 'Contagem de Incidentes de Segurança',
			self::DataBackupSuccess->value => 'Sucesso de Backup de Dados',
			self::SoftwareAssetOptimization->value => 'Otimização de Ativos de Software',
			self::NetworkPerformance->value => 'Desempenho da Rede',
			self::IncidentResponseTime->value => 'Tempo de Resposta a Incidentes',
			self::InfrastructureCostPerUser->value => 'Custo de Infraestrutura por Utilizador',
			self::OperationalEfficiency->value => 'Eficiência Operacional',
			self::StrategicInitiative->value => 'Iniciativa Estratégica',
			self::PolicyCompliance->value => 'Conformidade com Políticas',
			self::FacilityManagement->value => 'Gestão de Instalações',
			self::SustainabilityTarget->value => 'Meta de Sustentabilidade',
			self::VendorManagement->value => 'Gestão de Fornecedores',
			self::DocumentControl->value => 'Controlo de Documentos',
			self::BusinessContinuity->value => 'Continuidade de Negócios',
		];
	}

	public static function labelsEn(): array
	{
		return [
			self::Invoice->value => 'Invoice',
			self::Bill->value => 'Bill',
			self::Revenue->value => 'Revenue',
			self::Payment->value => 'Payment',
			self::GeneralLedgerAccuracy->value => 'General Ledger Accuracy',
			self::AccountsReceivableDays->value => 'Accounts Receivable Days',
			self::AccountsPayableEfficiency->value => 'Accounts Payable Efficiency',
			self::CostReduction->value => 'Cost Reduction',
			self::BudgetAdherence->value => 'Budget Adherence',
			self::CashFlowTarget->value => 'Cash Flow Target',
			self::AssetUtilization->value => 'Asset Utilization',
			self::AuditReadiness->value => 'Audit Readiness',
			self::TaxCompliance->value => 'Tax Compliance',
			self::FinancialCloseTime->value => 'Financial Close Time',
			self::ExpenseRatio->value => 'Expense Ratio',
			self::SalesQuota->value => 'Sales Quota',
			self::LeadConversion->value => 'Lead Conversion',
			self::CustomerAcquisitionCost->value => 'Customer Acquisition Cost',
			self::MarketShareGrowth->value => 'Market Share Growth',
			self::CustomerLifetimeValue->value => 'Customer Lifetime Value',
			self::CampaignROI->value => 'Campaign ROI',
			self::DealSize->value => 'Deal Size',
			self::SalesCycleLength->value => 'Sales Cycle Length',
			self::PipelineValue->value => 'Pipeline Value',
			self::MilestoneCompletion->value => 'Milestone Completion',
			self::ProjectOnTime->value => 'Project On Time',
			self::ProjectOnBudget->value => 'Project On Budget',
			self::DeliverableQuality->value => 'Deliverable Quality',
			self::ScopeAdherence->value => 'Scope Adherence',
			self::StakeholderSatisfaction->value => 'Stakeholder Satisfaction',
			self::ResourceUtilization->value => 'Resource Utilization',
			self::RiskMitigation->value => 'Risk Mitigation',
			self::TeamVelocity->value => 'Team Velocity',
			self::HeadcountManagement->value => 'Headcount Management',
			self::EmployeeRetention->value => 'Employee Retention',
			self::TrainingCompletion->value => 'Training Completion',
			self::WorkforceCostOptimization->value => 'Workforce Cost Optimization',
			self::SuccessionPlanning->value => 'Succession Planning',
			self::PerformanceReviewCompletion->value => 'Performance Review Completion',
			self::EmployeeEngagement->value => 'Employee Engagement',
			self::TimeToHire->value => 'Time to Hire',
			self::DiversityRatio->value => 'Diversity Ratio',
			self::SystemUptime->value => 'System Uptime',
			self::HelpDeskResolutionTime->value => 'Help Desk Resolution Time',
			self::ProjectDeployment->value => 'Project Deployment',
			self::SecurityIncidentCount->value => 'Security Incident Count',
			self::DataBackupSuccess->value => 'Data Backup Success',
			self::SoftwareAssetOptimization->value => 'Software Asset Optimization',
			self::NetworkPerformance->value => 'Network Performance',
			self::IncidentResponseTime->value => 'Incident Response Time',
			self::InfrastructureCostPerUser->value => 'Infrastructure Cost Per User',
			self::OperationalEfficiency->value => 'Operational Efficiency',
			self::StrategicInitiative->value => 'Strategic Initiative',
			self::PolicyCompliance->value => 'Policy Compliance',
			self::FacilityManagement->value => 'Facility Management',
			self::SustainabilityTarget->value => 'Sustainability Target',
			self::VendorManagement->value => 'Vendor Management',
			self::DocumentControl->value => 'Document Control',
			self::BusinessContinuity->value => 'Business Continuity',
		];
	}

	public static function labelsEs(): array
	{
		return [
			self::Invoice->value => 'Factura',
			self::Bill->value => 'Cuenta',
			self::Revenue->value => 'Ingresos',
			self::Payment->value => 'Pago',
			self::GeneralLedgerAccuracy->value => 'Precisión del Libro Mayor',
			self::AccountsReceivableDays->value => 'Días de Cuentas por Cobrar',
			self::AccountsPayableEfficiency->value => 'Eficiencia de Cuentas por Pagar',
			self::CostReduction->value => 'Reducción de Costos',
			self::BudgetAdherence->value => 'Cumplimiento Presupuestario',
			self::CashFlowTarget->value => 'Objetivo de Flujo de Caja',
			self::AssetUtilization->value => 'Utilización de Activos',
			self::AuditReadiness->value => 'Preparación para Auditoría',
			self::TaxCompliance->value => 'Cumplimiento Tributario',
			self::FinancialCloseTime->value => 'Tiempo de Cierre Financiero',
			self::ExpenseRatio->value => 'Ratio de Gastos',
			self::SalesQuota->value => 'Cuota de Ventas',
			self::LeadConversion->value => 'Conversión de Leads',
			self::CustomerAcquisitionCost->value => 'Costo de Adquisición de Cliente',
			self::MarketShareGrowth->value => 'Crecimiento de Cuota de Mercado',
			self::CustomerLifetimeValue->value => 'Valor de Vida del Cliente',
			self::CampaignROI->value => 'ROI de Campaña',
			self::DealSize->value => 'Tamaño de Negocio',
			self::SalesCycleLength->value => 'Duración del Ciclo de Ventas',
			self::PipelineValue->value => 'Valor del Pipeline',
			self::MilestoneCompletion->value => 'Finalización de Hito',
			self::ProjectOnTime->value => 'Proyecto a Tiempo',
			self::ProjectOnBudget->value => 'Proyecto en Presupuesto',
			self::DeliverableQuality->value => 'Calidad de Entregable',
			self::ScopeAdherence->value => 'Cumplimiento del Alcance',
			self::StakeholderSatisfaction->value => 'Satisfacción de Interesados',
			self::ResourceUtilization->value => 'Utilización de Recursos',
			self::RiskMitigation->value => 'Mitigación de Riesgos',
			self::TeamVelocity->value => 'Velocidad del Equipo',
			self::HeadcountManagement->value => 'Gestión de Personal',
			self::EmployeeRetention->value => 'Retención de Empleados',
			self::TrainingCompletion->value => 'Finalización de Formación',
			self::WorkforceCostOptimization->value => 'Optimización de Costos Laborales',
			self::SuccessionPlanning->value => 'Planificación de Sucesión',
			self::PerformanceReviewCompletion->value => 'Finalización de Evaluación de Desempeño',
			self::EmployeeEngagement->value => 'Compromiso de Empleados',
			self::TimeToHire->value => 'Tiempo de Contratación',
			self::DiversityRatio->value => 'Ratio de Diversidad',
			self::SystemUptime->value => 'Tiempo de Actividad del Sistema',
			self::HelpDeskResolutionTime->value => 'Tiempo de Resolución de Help Desk',
			self::ProjectDeployment->value => 'Despliegue de Proyecto',
			self::SecurityIncidentCount->value => 'Cantidad de Incidentes de Seguridad',
			self::DataBackupSuccess->value => 'Éxito de Copia de Seguridad',
			self::SoftwareAssetOptimization->value => 'Optimización de Activos de Software',
			self::NetworkPerformance->value => 'Rendimiento de Red',
			self::IncidentResponseTime->value => 'Tiempo de Respuesta a Incidentes',
			self::InfrastructureCostPerUser->value => 'Costo de Infraestructura por Usuario',
			self::OperationalEfficiency->value => 'Eficiencia Operativa',
			self::StrategicInitiative->value => 'Iniciativa Estratégica',
			self::PolicyCompliance->value => 'Cumplimiento de Políticas',
			self::FacilityManagement->value => 'Gestión de Instalaciones',
			self::SustainabilityTarget->value => 'Objetivo de Sostenibilidad',
			self::VendorManagement->value => 'Gestión de Proveedores',
			self::DocumentControl->value => 'Control de Documentos',
			self::BusinessContinuity->value => 'Continuidad del Negocio',
		];
	}

	public static function labelsAr(): array
	{
		return [
			self::Invoice->value => 'فاتورة',
			self::Bill->value => 'فاتورة/فاتورة شراء',
			self::Revenue->value => 'الإيرادات',
			self::Payment->value => 'دفعة',
			self::GeneralLedgerAccuracy->value => 'دقة دفتر الأستاذ العام',
			self::AccountsReceivableDays->value => 'أيام الذمم المدينة',
			self::AccountsPayableEfficiency->value => 'كفاءة الذمم الدائنة',
			self::CostReduction->value => 'خفض التكاليف',
			self::BudgetAdherence->value => 'الالتزام بالميزانية',
			self::CashFlowTarget->value => 'هدف التدفق النقدي',
			self::AssetUtilization->value => 'استخدام الأصول',
			self::AuditReadiness->value => 'جاهزية التدقيق',
			self::TaxCompliance->value => 'الامتثال الضريبي',
			self::FinancialCloseTime->value => 'وقت الإغلاق المالي',
			self::ExpenseRatio->value => 'نسبة المصروفات',
			self::SalesQuota->value => 'حصة المبيعات',
			self::LeadConversion->value => 'تحويل العملاء المحتملين',
			self::CustomerAcquisitionCost->value => 'تكلفة اكتساب العميل',
			self::MarketShareGrowth->value => 'نمو الحصة السوقية',
			self::CustomerLifetimeValue->value => 'قيمة العميل مدى الحياة',
			self::CampaignROI->value => 'عائد الاستثمار من الحملة',
			self::DealSize->value => 'حجم الصفقة',
			self::SalesCycleLength->value => 'طول دورة المبيعات',
			self::PipelineValue->value => 'قيمة خط الأنابيب',
			self::MilestoneCompletion->value => 'إتمام المرحلة',
			self::ProjectOnTime->value => 'المشروع في الوقت المحدد',
			self::ProjectOnBudget->value => 'المشروع ضمن الميزانية',
			self::DeliverableQuality->value => 'جودة المنتج التسليمي',
			self::ScopeAdherence->value => 'الالتزام بالنطاق',
			self::StakeholderSatisfaction->value => 'رضا أصحاب المصلحة',
			self::ResourceUtilization->value => 'استخدام الموارد',
			self::RiskMitigation->value => 'التخفيف من المخاطر',
			self::TeamVelocity->value => 'سرعة الفريق',
			self::HeadcountManagement->value => 'إدارة عدد الموظفين',
			self::EmployeeRetention->value => 'الاحتفاظ بالموظفين',
			self::TrainingCompletion->value => 'إتمام التدريب',
			self::WorkforceCostOptimization->value => 'تحسين تكاليف القوى العاملة',
			self::SuccessionPlanning->value => 'تخطيط التعاقب',
			self::PerformanceReviewCompletion->value => 'إتمام مراجعة الأداء',
			self::EmployeeEngagement->value => 'مشاركة الموظفين',
			self::TimeToHire->value => 'وقت التوظيف',
			self::DiversityRatio->value => 'نسبة التنوع',
			self::SystemUptime->value => 'وقت تشغيل النظام',
			self::HelpDeskResolutionTime->value => 'وقت حل مكتب المساعدة',
			self::ProjectDeployment->value => 'نشر المشروع',
			self::SecurityIncidentCount->value => 'عدد حوادث الأمان',
			self::DataBackupSuccess->value => 'نجاح نسخ البيانات الاحتياطية',
			self::SoftwareAssetOptimization->value => 'تحسين أصول البرمجيات',
			self::NetworkPerformance->value => 'أداء الشبكة',
			self::IncidentResponseTime->value => 'وقت الاستجابة للحوادث',
			self::InfrastructureCostPerUser->value => 'تكلفة البنية التحتية لكل مستخدم',
			self::OperationalEfficiency->value => 'الكفاءة التشغيلية',
			self::StrategicInitiative->value => 'المبادرة الاستراتيجية',
			self::PolicyCompliance->value => 'الامتثال للسياسات',
			self::FacilityManagement->value => 'إدارة المنشآت',
			self::SustainabilityTarget->value => 'هدف الاستدامة',
			self::VendorManagement->value => 'إدارة الموردين',
			self::DocumentControl->value => 'التحكم في الوثائق',
			self::BusinessContinuity->value => 'استمرارية الأعمال',
		];
	}

	public static function labelsDa(): array
	{
		return [
			self::Invoice->value => 'Faktura',
			self::Bill->value => 'Regning',
			self::Revenue->value => 'Indtægt',
			self::Payment->value => 'Betaling',
			self::GeneralLedgerAccuracy->value => 'Nøjagtighed af hovedbog',
			self::AccountsReceivableDays->value => 'Kundedage',
			self::AccountsPayableEfficiency->value => 'Effektivitet af kreditorer',
			self::CostReduction->value => 'Omkostningsreduktion',
			self::BudgetAdherence->value => 'Overholdelse af budget',
			self::CashFlowTarget->value => 'Cash flow-mål',
			self::AssetUtilization->value => 'Udnyttelse af aktiver',
			self::AuditReadiness->value => 'Revisionparathed',
			self::TaxCompliance->value => 'Skatteoverholdelse',
			self::FinancialCloseTime->value => 'Finansiel afslutningstid',
			self::ExpenseRatio->value => 'Omkostningsforhold',
			self::SalesQuota->value => 'Salgskvote',
			self::LeadConversion->value => 'Leadkonvertering',
			self::CustomerAcquisitionCost->value => 'Kundehvervelsesomkostning',
			self::MarketShareGrowth->value => 'Markedsandelsvækst',
			self::CustomerLifetimeValue->value => 'Kundens levetidsværdi',
			self::CampaignROI->value => 'Kampagne ROI',
			self::DealSize->value => 'Aftalestørrelse',
			self::SalesCycleLength->value => 'Salgscykluslængde',
			self::PipelineValue->value => 'Pipeline-værdi',
			self::MilestoneCompletion->value => 'Milepælsafslutning',
			self::ProjectOnTime->value => 'Projekt til tiden',
			self::ProjectOnBudget->value => 'Projekt på budget',
			self::DeliverableQuality->value => 'Leverancekvalitet',
			self::ScopeAdherence->value => 'Overholdelse af omfang',
			self::StakeholderSatisfaction->value => 'Interessenttilfredshed',
			self::ResourceUtilization->value => 'Ressourceudnyttelse',
			self::RiskMitigation->value => 'Risikoreduktion',
			self::TeamVelocity->value => 'Teamhastighed',
			self::HeadcountManagement->value => 'Personaleadministration',
			self::EmployeeRetention->value => 'Medarbejderbevarelse',
			self::TrainingCompletion->value => 'Uddannelsesgennemførelse',
			self::WorkforceCostOptimization->value => 'Optimering af arbejdsstyrkens omkostninger',
			self::SuccessionPlanning->value => 'Efterfølgerplanlægning',
			self::PerformanceReviewCompletion->value => 'Gennemførelse af performancevurdering',
			self::EmployeeEngagement->value => 'Medarbejderengagement',
			self::TimeToHire->value => 'Ansættelsestid',
			self::DiversityRatio->value => 'Diversitetsforhold',
			self::SystemUptime->value => 'System driftstid',
			self::HelpDeskResolutionTime->value => 'Help Desk løsningstid',
			self::ProjectDeployment->value => 'Projektimplementering',
			self::SecurityIncidentCount->value => 'Antal sikkerhedshændelser',
			self::DataBackupSuccess->value => 'Succes med databackup',
			self::SoftwareAssetOptimization->value => 'Optimering af softwareaktiver',
			self::NetworkPerformance->value => 'Netværksydelse',
			self::IncidentResponseTime->value => 'Reaktionstid på hændelser',
			self::InfrastructureCostPerUser->value => 'Infrastrukturomkostning pr. bruger',
			self::OperationalEfficiency->value => 'Operativ effektivitet',
			self::StrategicInitiative->value => 'Strategisk initiativ',
			self::PolicyCompliance->value => 'Overholdelse af politikker',
			self::FacilityManagement->value => 'Facilitetsstyring',
			self::SustainabilityTarget->value => 'Bæredygtighedsmål',
			self::VendorManagement->value => 'Leverandørstyring',
			self::DocumentControl->value => 'Dokumentkontrol',
			self::BusinessContinuity->value => 'Forretningskontinuitet',
		];
	}

	public static function labelsDe(): array
	{
		return [
			self::Invoice->value => 'Rechnung',
			self::Bill->value => 'Rechnung (Einkauf)',
			self::Revenue->value => 'Umsatz',
			self::Payment->value => 'Zahlung',
			self::GeneralLedgerAccuracy->value => 'Hauptbuchgenauigkeit',
			self::AccountsReceivableDays->value => 'Debitorenlaufzeit',
			self::AccountsPayableEfficiency->value => 'Kreditoreneffizienz',
			self::CostReduction->value => 'Kostenreduzierung',
			self::BudgetAdherence->value => 'Budgeteinhaltung',
			self::CashFlowTarget->value => 'Cashflow-Ziel',
			self::AssetUtilization->value => 'Anlagenauslastung',
			self::AuditReadiness->value => 'Auditbereitschaft',
			self::TaxCompliance->value => 'Steuercompliance',
			self::FinancialCloseTime->value => 'Finanzabschlusszeit',
			self::ExpenseRatio->value => 'Kostenquote',
			self::SalesQuota->value => 'Verkaufsquote',
			self::LeadConversion->value => 'Lead-Konvertierung',
			self::CustomerAcquisitionCost->value => 'Kundenakquisitionskosten',
			self::MarketShareGrowth->value => 'Marktanteilswachstum',
			self::CustomerLifetimeValue->value => 'Customer Lifetime Value',
			self::CampaignROI->value => 'Kampagnen-ROI',
			self::DealSize->value => 'Deal-Größe',
			self::SalesCycleLength->value => 'Vertriebszykluslänge',
			self::PipelineValue->value => 'Pipeline-Wert',
			self::MilestoneCompletion->value => 'Meilensteinabschluss',
			self::ProjectOnTime->value => 'Projekt termingerecht',
			self::ProjectOnBudget->value => 'Projekt im Budget',
			self::DeliverableQuality->value => 'Lieferqualität',
			self::ScopeAdherence->value => 'Scope-Einhaltung',
			self::StakeholderSatisfaction->value => 'Stakeholder-Zufriedenheit',
			self::ResourceUtilization->value => 'Ressourcenauslastung',
			self::RiskMitigation->value => 'Risikominderung',
			self::TeamVelocity->value => 'Team-Geschwindigkeit',
			self::HeadcountManagement->value => 'Personalbestandsmanagement',
			self::EmployeeRetention->value => 'Mitarbeiterbindung',
			self::TrainingCompletion->value => 'Schulungsabschluss',
			self::WorkforceCostOptimization->value => 'Arbeitskräftekostenoptimierung',
			self::SuccessionPlanning->value => 'Nachfolgeplanung',
			self::PerformanceReviewCompletion->value => 'Leistungsbeurteilungsabschluss',
			self::EmployeeEngagement->value => 'Mitarbeiterengagement',
			self::TimeToHire->value => 'Einstellungszeit',
			self::DiversityRatio->value => 'Diversitätsquote',
			self::SystemUptime->value => 'Systemverfügbarkeit',
			self::HelpDeskResolutionTime->value => 'Help-Desk-Lösungszeit',
			self::ProjectDeployment->value => 'Projektbereitstellung',
			self::SecurityIncidentCount->value => 'Anzahl Sicherheitsvorfälle',
			self::DataBackupSuccess->value => 'Datenbackup-Erfolg',
			self::SoftwareAssetOptimization->value => 'Software-Asset-Optimierung',
			self::NetworkPerformance->value => 'Netzwerkleistung',
			self::IncidentResponseTime->value => 'Vorfallreaktionszeit',
			self::InfrastructureCostPerUser->value => 'Infrastrukturkosten pro Benutzer',
			self::OperationalEfficiency->value => 'Betriebseffizienz',
			self::StrategicInitiative->value => 'Strategische Initiative',
			self::PolicyCompliance->value => 'Richtliniencompliance',
			self::FacilityManagement->value => 'Gebäudemanagement',
			self::SustainabilityTarget->value => 'Nachhaltigkeitsziel',
			self::VendorManagement->value => 'Lieferantenmanagement',
			self::DocumentControl->value => 'Dokumentensteuerung',
			self::BusinessContinuity->value => 'Geschäftskontinuität',
		];
	}

	public static function labelsFr(): array
	{
		return [
			self::Invoice->value => 'Facture',
			self::Bill->value => 'Facture (achat)',
			self::Revenue->value => 'Chiffre d\'affaires',
			self::Payment->value => 'Paiement',
			self::GeneralLedgerAccuracy->value => 'Exactitude du grand livre',
			self::AccountsReceivableDays->value => 'Jours de créances clients',
			self::AccountsPayableEfficiency->value => 'Efficacité des comptes fournisseurs',
			self::CostReduction->value => 'Réduction des coûts',
			self::BudgetAdherence->value => 'Respect du budget',
			self::CashFlowTarget->value => 'Objectif de trésorerie',
			self::AssetUtilization->value => 'Utilisation des actifs',
			self::AuditReadiness->value => 'Préparation à l\'audit',
			self::TaxCompliance->value => 'Conformité fiscale',
			self::FinancialCloseTime->value => 'Délai de clôture financière',
			self::ExpenseRatio->value => 'Ratio de dépenses',
			self::SalesQuota->value => 'Quota de ventes',
			self::LeadConversion->value => 'Conversion de leads',
			self::CustomerAcquisitionCost->value => 'Coût d\'acquisition client',
			self::MarketShareGrowth->value => 'Croissance de part de marché',
			self::CustomerLifetimeValue->value => 'Valeur client à vie',
			self::CampaignROI->value => 'ROI de campagne',
			self::DealSize->value => 'Taille de transaction',
			self::SalesCycleLength->value => 'Durée du cycle de vente',
			self::PipelineValue->value => 'Valeur du pipeline',
			self::MilestoneCompletion->value => 'Achèvement de jalon',
			self::ProjectOnTime->value => 'Projet dans les délais',
			self::ProjectOnBudget->value => 'Projet dans le budget',
			self::DeliverableQuality->value => 'Qualité des livrables',
			self::ScopeAdherence->value => 'Respect du périmètre',
			self::StakeholderSatisfaction->value => 'Satisfaction des parties prenantes',
			self::ResourceUtilization->value => 'Utilisation des ressources',
			self::RiskMitigation->value => 'Atténuation des risques',
			self::TeamVelocity->value => 'Vélocité de l\'équipe',
			self::HeadcountManagement->value => 'Gestion des effectifs',
			self::EmployeeRetention->value => 'Rétention des employés',
			self::TrainingCompletion->value => 'Achèvement de la formation',
			self::WorkforceCostOptimization->value => 'Optimisation des coûts de main-d\'œuvre',
			self::SuccessionPlanning->value => 'Planification de la relève',
			self::PerformanceReviewCompletion->value => 'Achèvement de l\'évaluation des performances',
			self::EmployeeEngagement->value => 'Engagement des employés',
			self::TimeToHire->value => 'Délai de recrutement',
			self::DiversityRatio->value => 'Ratio de diversité',
			self::SystemUptime->value => 'Temps de disponibilité du système',
			self::HelpDeskResolutionTime->value => 'Délai de résolution du help desk',
			self::ProjectDeployment->value => 'Déploiement du projet',
			self::SecurityIncidentCount->value => 'Nombre d\'incidents de sécurité',
			self::DataBackupSuccess->value => 'Succès de sauvegarde des données',
			self::SoftwareAssetOptimization->value => 'Optimisation des actifs logiciels',
			self::NetworkPerformance->value => 'Performance du réseau',
			self::IncidentResponseTime->value => 'Temps de réponse aux incidents',
			self::InfrastructureCostPerUser->value => 'Coût d\'infrastructure par utilisateur',
			self::OperationalEfficiency->value => 'Efficacité opérationnelle',
			self::StrategicInitiative->value => 'Initiative stratégique',
			self::PolicyCompliance->value => 'Conformité aux politiques',
			self::FacilityManagement->value => 'Gestion des installations',
			self::SustainabilityTarget->value => 'Objectif de durabilité',
			self::VendorManagement->value => 'Gestion des fournisseurs',
			self::DocumentControl->value => 'Contrôle des documents',
			self::BusinessContinuity->value => 'Continuité des activités',
		];
	}

	public static function labelsHe(): array
	{
		return [
			self::Invoice->value => 'חשבונית',
			self::Bill->value => 'חשבון',
			self::Revenue->value => 'הכנסות',
			self::Payment->value => 'תשלום',
			self::GeneralLedgerAccuracy->value => 'דיוק ספר ראשי',
			self::AccountsReceivableDays->value => 'ימי חייבים',
			self::AccountsPayableEfficiency->value => 'יעילות נושים',
			self::CostReduction->value => 'הפחתת עלויות',
			self::BudgetAdherence->value => 'עמידה בתקציב',
			self::CashFlowTarget->value => 'יעד תזרים מזומנים',
			self::AssetUtilization->value => 'ניצול נכסים',
			self::AuditReadiness->value => 'מוכנות לביקורת',
			self::TaxCompliance->value => 'עמידה בדרישות מס',
			self::FinancialCloseTime->value => 'זמן סגירה פיננסית',
			self::ExpenseRatio->value => 'יחס הוצאות',
			self::SalesQuota->value => 'מכסת מכירות',
			self::LeadConversion->value => 'המרת לידים',
			self::CustomerAcquisitionCost->value => 'עלות רכישת לקוח',
			self::MarketShareGrowth->value => 'גידול בנתח שוק',
			self::CustomerLifetimeValue->value => 'ערך חיי לקוח',
			self::CampaignROI->value => 'תשואה על השקעה בקמפיין',
			self::DealSize->value => 'גודל עסקה',
			self::SalesCycleLength->value => 'אורך מחזור מכירות',
			self::PipelineValue->value => 'ערך צינור מכירות',
			self::MilestoneCompletion->value => 'השלמת אבן דרך',
			self::ProjectOnTime->value => 'פרויקט בזמן',
			self::ProjectOnBudget->value => 'פרויקט בתקציב',
			self::DeliverableQuality->value => 'איכות מוצר',
			self::ScopeAdherence->value => 'עמידה בהיקף',
			self::StakeholderSatisfaction->value => 'שביעות רצון בעלי עניין',
			self::ResourceUtilization->value => 'ניצול משאבים',
			self::RiskMitigation->value => 'הפחתת סיכונים',
			self::TeamVelocity->value => 'מהירות צוות',
			self::HeadcountManagement->value => 'ניהול כוח אדם',
			self::EmployeeRetention->value => 'שמירת עובדים',
			self::TrainingCompletion->value => 'השלמת הכשרה',
			self::WorkforceCostOptimization->value => 'אופטימיזציית עלויות כוח אדם',
			self::SuccessionPlanning->value => 'תכנון רצף',
			self::PerformanceReviewCompletion->value => 'השלמת סקירת ביצועים',
			self::EmployeeEngagement->value => 'מעורבות עובדים',
			self::TimeToHire->value => 'זמן לגיוס',
			self::DiversityRatio->value => 'יחס גיוון',
			self::SystemUptime->value => 'זמן פעילות מערכת',
			self::HelpDeskResolutionTime->value => 'זמן פתרון שירות',
			self::ProjectDeployment->value => 'פריסת פרויקט',
			self::SecurityIncidentCount->value => 'מספר אירועי אבטחה',
			self::DataBackupSuccess->value => 'הצלחת גיבוי נתונים',
			self::SoftwareAssetOptimization->value => 'אופטימיזציית נכסי תוכנה',
			self::NetworkPerformance->value => 'ביצועי רשת',
			self::IncidentResponseTime->value => 'זמן תגובה לאירוע',
			self::InfrastructureCostPerUser->value => 'עלות תשתית למשתמש',
			self::OperationalEfficiency->value => 'יעילות תפעולית',
			self::StrategicInitiative->value => 'יוזמה אסטרטגית',
			self::PolicyCompliance->value => 'עמידה במדיניות',
			self::FacilityManagement->value => 'ניהול מתקנים',
			self::SustainabilityTarget->value => 'יעד קיימות',
			self::VendorManagement->value => 'ניהול ספקים',
			self::DocumentControl->value => 'בקרת מסמכים',
			self::BusinessContinuity->value => 'רציפות עסקית',
		];
	}

	public static function labelsIt(): array
	{
		return [
			self::Invoice->value => 'Fattura',
			self::Bill->value => 'Fattura (acquisto)',
			self::Revenue->value => 'Ricavi',
			self::Payment->value => 'Pagamento',
			self::GeneralLedgerAccuracy->value => 'Accuratezza del libro mastro',
			self::AccountsReceivableDays->value => 'Giorni crediti clienti',
			self::AccountsPayableEfficiency->value => 'Efficienza dei debiti',
			self::CostReduction->value => 'Riduzione dei costi',
			self::BudgetAdherence->value => 'Rispetto del budget',
			self::CashFlowTarget->value => 'Obiettivo di cash flow',
			self::AssetUtilization->value => 'Utilizzo delle attività',
			self::AuditReadiness->value => 'Preparazione alle verifiche',
			self::TaxCompliance->value => 'Conformità fiscale',
			self::FinancialCloseTime->value => 'Tempo di chiusura finanziaria',
			self::ExpenseRatio->value => 'Rapporto spese',
			self::SalesQuota->value => 'Quota di vendita',
			self::LeadConversion->value => 'Conversione dei lead',
			self::CustomerAcquisitionCost->value => 'Costo di acquisizione cliente',
			self::MarketShareGrowth->value => 'Crescita della quota di mercato',
			self::CustomerLifetimeValue->value => 'Valore del cliente nel tempo',
			self::CampaignROI->value => 'ROI della campagna',
			self::DealSize->value => 'Dimensione dell\'affare',
			self::SalesCycleLength->value => 'Lunghezza ciclo di vendita',
			self::PipelineValue->value => 'Valore della pipeline',
			self::MilestoneCompletion->value => 'Completamento traguardo',
			self::ProjectOnTime->value => 'Progetto in tempo',
			self::ProjectOnBudget->value => 'Progetto nel budget',
			self::DeliverableQuality->value => 'Qualità delle consegne',
			self::ScopeAdherence->value => 'Rispetto dello scope',
			self::StakeholderSatisfaction->value => 'Soddisfazione degli stakeholder',
			self::ResourceUtilization->value => 'Utilizzo delle risorse',
			self::RiskMitigation->value => 'Mitigazione del rischio',
			self::TeamVelocity->value => 'Velocità del team',
			self::HeadcountManagement->value => 'Gestione del personale',
			self::EmployeeRetention->value => 'Fidelizzazione dei dipendenti',
			self::TrainingCompletion->value => 'Completamento della formazione',
			self::WorkforceCostOptimization->value => 'Ottimizzazione dei costi del personale',
			self::SuccessionPlanning->value => 'Pianificazione delle successioni',
			self::PerformanceReviewCompletion->value => 'Completamento della valutazione delle prestazioni',
			self::EmployeeEngagement->value => 'Coinvolgimento dei dipendenti',
			self::TimeToHire->value => 'Tempo di assunzione',
			self::DiversityRatio->value => 'Rapporto di diversità',
			self::SystemUptime->value => 'Tempo di attività del sistema',
			self::HelpDeskResolutionTime->value => 'Tempo di risoluzione dell\'help desk',
			self::ProjectDeployment->value => 'Distribuzione del progetto',
			self::SecurityIncidentCount->value => 'Numero di incidenti di sicurezza',
			self::DataBackupSuccess->value => 'Successo del backup dati',
			self::SoftwareAssetOptimization->value => 'Ottimizzazione dei beni software',
			self::NetworkPerformance->value => 'Prestazioni di rete',
			self::IncidentResponseTime->value => 'Tempo di risposta agli incidenti',
			self::InfrastructureCostPerUser->value => 'Costo infrastruttura per utente',
			self::OperationalEfficiency->value => 'Efficienza operativa',
			self::StrategicInitiative->value => 'Iniziativa strategica',
			self::PolicyCompliance->value => 'Conformità alle politiche',
			self::FacilityManagement->value => 'Gestione delle strutture',
			self::SustainabilityTarget->value => 'Obiettivo di sostenibilità',
			self::VendorManagement->value => 'Gestione dei fornitori',
			self::DocumentControl->value => 'Controllo documenti',
			self::BusinessContinuity->value => 'Continuità operativa',
		];
	}

	public static function labelsJa(): array
	{
		return [
			self::Invoice->value => '請求書',
			self::Bill->value => '支払請求書',
			self::Revenue->value => '売上',
			self::Payment->value => '支払い',
			self::GeneralLedgerAccuracy->value => '総勘定元帳精度',
			self::AccountsReceivableDays->value => '売上債権回転期間',
			self::AccountsPayableEfficiency->value => '買掛金効率',
			self::CostReduction->value => 'コスト削減',
			self::BudgetAdherence->value => '予算遵守',
			self::CashFlowTarget->value => 'キャッシュフロー目標',
			self::AssetUtilization->value => '資産利用率',
			self::AuditReadiness->value => '監査対応準備',
			self::TaxCompliance->value => '税務コンプライアンス',
			self::FinancialCloseTime->value => '財務決算時間',
			self::ExpenseRatio->value => '費用比率',
			self::SalesQuota->value => '販売ノルマ',
			self::LeadConversion->value => 'リードコンバージョン',
			self::CustomerAcquisitionCost->value => '顧客獲得コスト',
			self::MarketShareGrowth->value => '市場シェア成長',
			self::CustomerLifetimeValue->value => '顧客生涯価値',
			self::CampaignROI->value => 'キャンペーンROI',
			self::DealSize->value => '取引規模',
			self::SalesCycleLength->value => '販売サイクル長',
			self::PipelineValue->value => 'パイプライン価値',
			self::MilestoneCompletion->value => 'マイルストーン達成',
			self::ProjectOnTime->value => 'プロジェクト納期遵守',
			self::ProjectOnBudget->value => 'プロジェクト予算内実行',
			self::DeliverableQuality->value => '成果物品質',
			self::ScopeAdherence->value => '範囲遵守',
			self::StakeholderSatisfaction->value => 'ステークホルダー満足度',
			self::ResourceUtilization->value => 'リソース利用率',
			self::RiskMitigation->value => 'リスク軽減',
			self::TeamVelocity->value => 'チームベロシティ',
			self::HeadcountManagement->value => '人員管理',
			self::EmployeeRetention->value => '従業員定着率',
			self::TrainingCompletion->value => '研修完了',
			self::WorkforceCostOptimization->value => '人件費最適化',
			self::SuccessionPlanning->value => '後継者計画',
			self::PerformanceReviewCompletion->value => '業績評価完了',
			self::EmployeeEngagement->value => '従業員エンゲージメント',
			self::TimeToHire->value => '採用までの時間',
			self::DiversityRatio->value => '多様性比率',
			self::SystemUptime->value => 'システム稼働時間',
			self::HelpDeskResolutionTime->value => 'ヘルプデスク解決時間',
			self::ProjectDeployment->value => 'プロジェクト展開',
			self::SecurityIncidentCount->value => 'セキュリティインシデント数',
			self::DataBackupSuccess->value => 'データバックアップ成功率',
			self::SoftwareAssetOptimization->value => 'ソフトウェア資産最適化',
			self::NetworkPerformance->value => 'ネットワークパフォーマンス',
			self::IncidentResponseTime->value => 'インシデント対応時間',
			self::InfrastructureCostPerUser->value => 'ユーザーあたりインフラコスト',
			self::OperationalEfficiency->value => '業務効率',
			self::StrategicInitiative->value => '戦略的イニシアチブ',
			self::PolicyCompliance->value => 'ポリシー遵守',
			self::FacilityManagement->value => '施設管理',
			self::SustainabilityTarget->value => '持続可能性目標',
			self::VendorManagement->value => 'ベンダー管理',
			self::DocumentControl->value => '文書管理',
			self::BusinessContinuity->value => '事業継続',
		];
	}

	public static function labelsNl(): array
	{
		return [
			self::Invoice->value => 'Factuur',
			self::Bill->value => 'Rekening',
			self::Revenue->value => 'Omzet',
			self::Payment->value => 'Betaling',
			self::GeneralLedgerAccuracy->value => 'Nauwkeurigheid grootboek',
			self::AccountsReceivableDays->value => 'Debiteurendagen',
			self::AccountsPayableEfficiency->value => 'Efficiëntie crediteuren',
			self::CostReduction->value => 'Kostenreductie',
			self::BudgetAdherence->value => 'Budgetnaleving',
			self::CashFlowTarget->value => 'Cashflow-doel',
			self::AssetUtilization->value => 'Middelengebruik',
			self::AuditReadiness->value => 'Auditgereedheid',
			self::TaxCompliance->value => 'Fiscale naleving',
			self::FinancialCloseTime->value => 'Financiële sluitingstijd',
			self::ExpenseRatio->value => 'Kostenratio',
			self::SalesQuota->value => 'Verkoopquota',
			self::LeadConversion->value => 'Leadconversie',
			self::CustomerAcquisitionCost->value => 'Klantverwervingskosten',
			self::MarketShareGrowth->value => 'Marktaandeelgroei',
			self::CustomerLifetimeValue->value => 'Levenslange klantwaarde',
			self::CampaignROI->value => 'Campagne-ROI',
			self::DealSize->value => 'Dealgrootte',
			self::SalesCycleLength->value => 'Verkoopcycluslengte',
			self::PipelineValue->value => 'Pipelinewaarde',
			self::MilestoneCompletion->value => 'Mijlpaalvoltooiing',
			self::ProjectOnTime->value => 'Project op tijd',
			self::ProjectOnBudget->value => 'Project binnen budget',
			self::DeliverableQuality->value => 'Leveringskwaliteit',
			self::ScopeAdherence->value => 'Scopenaleving',
			self::StakeholderSatisfaction->value => 'Stakeholdertevredenheid',
			self::ResourceUtilization->value => 'Middelengebruik',
			self::RiskMitigation->value => 'Risicobeperking',
			self::TeamVelocity->value => 'Teamsnelheid',
			self::HeadcountManagement->value => 'Personeelsbeheer',
			self::EmployeeRetention->value => 'Medewerkerbehoud',
			self::TrainingCompletion->value => 'Trainingvoltooiing',
			self::WorkforceCostOptimization->value => 'Arbeidskostenoptimalisatie',
			self::SuccessionPlanning->value => 'Opvolgingsplanning',
			self::PerformanceReviewCompletion->value => 'Prestatiebeoordelingsvoltooiing',
			self::EmployeeEngagement->value => 'Medewerkerbetrokkenheid',
			self::TimeToHire->value => 'Aanwervingstijd',
			self::DiversityRatio->value => 'Diversiteitsratio',
			self::SystemUptime->value => 'Systeembeschikbaarheid',
			self::HelpDeskResolutionTime->value => 'Helpdesk-oplossingstijd',
			self::ProjectDeployment->value => 'Projectimplementatie',
			self::SecurityIncidentCount->value => 'Aantal beveiligingsincidenten',
			self::DataBackupSuccess->value => 'Gegevensbackup-succes',
			self::SoftwareAssetOptimization->value => 'Softwaremiddelenoptimalisatie',
			self::NetworkPerformance->value => 'Netwerkprestaties',
			self::IncidentResponseTime->value => 'Incidentresponsetijd',
			self::InfrastructureCostPerUser->value => 'Infrastructuurkosten per gebruiker',
			self::OperationalEfficiency->value => 'Operationele efficiëntie',
			self::StrategicInitiative->value => 'Strategisch initiatief',
			self::PolicyCompliance->value => 'Beleidsnaleving',
			self::FacilityManagement->value => 'Facilitair beheer',
			self::SustainabilityTarget->value => 'Duurzaamheidsdoel',
			self::VendorManagement->value => 'Leveranciersbeheer',
			self::DocumentControl->value => 'Documentbeheer',
			self::BusinessContinuity->value => 'Bedrijfscontinuïteit',
		];
	}

	public static function labelsPl(): array
	{
		return [
			self::Invoice->value => 'Faktura',
			self::Bill->value => 'Rachunek',
			self::Revenue->value => 'Przychód',
			self::Payment->value => 'Płatność',
			self::GeneralLedgerAccuracy->value => 'Dokładność księgi głównej',
			self::AccountsReceivableDays->value => 'Dni należności',
			self::AccountsPayableEfficiency->value => 'Wydajność zobowiązań',
			self::CostReduction->value => 'Redukcja kosztów',
			self::BudgetAdherence->value => 'Przestrzeganie budżetu',
			self::CashFlowTarget->value => 'Cel przepływów pieniężnych',
			self::AssetUtilization->value => 'Wykorzystanie aktywów',
			self::AuditReadiness->value => 'Gotowość do audytu',
			self::TaxCompliance->value => 'Zgodność podatkowa',
			self::FinancialCloseTime->value => 'Czas zamknięcia finansowego',
			self::ExpenseRatio->value => 'Wskaźnik kosztów',
			self::SalesQuota->value => 'Kwota sprzedaży',
			self::LeadConversion->value => 'Konwersja leadów',
			self::CustomerAcquisitionCost->value => 'Koszt pozyskania klienta',
			self::MarketShareGrowth->value => 'Wzrost udziału w rynku',
			self::CustomerLifetimeValue->value => 'Wartość życiowa klienta',
			self::CampaignROI->value => 'ROI kampanii',
			self::DealSize->value => 'Wielkość transakcji',
			self::SalesCycleLength->value => 'Długość cyklu sprzedaży',
			self::PipelineValue->value => 'Wartość pipeline',
			self::MilestoneCompletion->value => 'Ukończenie kamienia milowego',
			self::ProjectOnTime->value => 'Projekt na czas',
			self::ProjectOnBudget->value => 'Projekt w budżecie',
			self::DeliverableQuality->value => 'Jakość dostawy',
			self::ScopeAdherence->value => 'Przestrzeganie zakresu',
			self::StakeholderSatisfaction->value => 'Zadowolenie interesariuszy',
			self::ResourceUtilization->value => 'Wykorzystanie zasobów',
			self::RiskMitigation->value => 'Łagodzenie ryzyka',
			self::TeamVelocity->value => 'Prędkość zespołu',
			self::HeadcountManagement->value => 'Zarządzanie zatrudnieniem',
			self::EmployeeRetention->value => 'Retencja pracowników',
			self::TrainingCompletion->value => 'Ukończenie szkolenia',
			self::WorkforceCostOptimization->value => 'Optymalizacja kosztów pracy',
			self::SuccessionPlanning->value => 'Planowanie sukcesji',
			self::PerformanceReviewCompletion->value => 'Ukończenie przeglądu wydajności',
			self::EmployeeEngagement->value => 'Zaangażowanie pracowników',
			self::TimeToHire->value => 'Czas zatrudnienia',
			self::DiversityRatio->value => 'Wskaźnik różnorodności',
			self::SystemUptime->value => 'Czas działania systemu',
			self::HelpDeskResolutionTime->value => 'Czas rozwiązywania problemów help desk',
			self::ProjectDeployment->value => 'Wdrożenie projektu',
			self::SecurityIncidentCount->value => 'Liczba incydentów bezpieczeństwa',
			self::DataBackupSuccess->value => 'Sukces kopii zapasowych danych',
			self::SoftwareAssetOptimization->value => 'Optymalizacja zasobów oprogramowania',
			self::NetworkPerformance->value => 'Wydajność sieci',
			self::IncidentResponseTime->value => 'Czas reakcji na incydenty',
			self::InfrastructureCostPerUser->value => 'Koszt infrastruktury na użytkownika',
			self::OperationalEfficiency->value => 'Wydajność operacyjna',
			self::StrategicInitiative->value => 'Inicjatywa strategiczna',
			self::PolicyCompliance->value => 'Zgodność z politykami',
			self::FacilityManagement->value => 'Zarządzanie obiektami',
			self::SustainabilityTarget->value => 'Cel zrównoważonego rozwoju',
			self::VendorManagement->value => 'Zarządzanie dostawcami',
			self::DocumentControl->value => 'Kontrola dokumentów',
			self::BusinessContinuity->value => 'Ciągłość działania',
		];
	}

	public static function labelsRu(): array
	{
		return [
			self::Invoice->value => 'Счет',
			self::Bill->value => 'Счет (к оплате)',
			self::Revenue->value => 'Выручка',
			self::Payment->value => 'Платеж',
			self::GeneralLedgerAccuracy->value => 'Точность главной книги',
			self::AccountsReceivableDays->value => 'Дни дебиторской задолженности',
			self::AccountsPayableEfficiency->value => 'Эффективность кредиторской задолженности',
			self::CostReduction->value => 'Снижение затрат',
			self::BudgetAdherence->value => 'Соблюдение бюджета',
			self::CashFlowTarget->value => 'Цель по денежному потоку',
			self::AssetUtilization->value => 'Использование активов',
			self::AuditReadiness->value => 'Готовность к аудиту',
			self::TaxCompliance->value => 'Налоговая дисциплина',
			self::FinancialCloseTime->value => 'Время финансового закрытия',
			self::ExpenseRatio->value => 'Коэффициент расходов',
			self::SalesQuota->value => 'Квота продаж',
			self::LeadConversion->value => 'Конверсия лидов',
			self::CustomerAcquisitionCost->value => 'Стоимость привлечения клиента',
			self::MarketShareGrowth->value => 'Рост доли рынка',
			self::CustomerLifetimeValue->value => 'Пожизненная ценность клиента',
			self::CampaignROI->value => 'ROI кампании',
			self::DealSize->value => 'Размер сделки',
			self::SalesCycleLength->value => 'Длина цикла продаж',
			self::PipelineValue->value => 'Стоимость воронки продаж',
			self::MilestoneCompletion->value => 'Завершение этапа',
			self::ProjectOnTime->value => 'Проект в срок',
			self::ProjectOnBudget->value => 'Проект в рамках бюджета',
			self::DeliverableQuality->value => 'Качество поставки',
			self::ScopeAdherence->value => 'Соблюдение объема работ',
			self::StakeholderSatisfaction->value => 'Удовлетворенность стейкхолдеров',
			self::ResourceUtilization->value => 'Использование ресурсов',
			self::RiskMitigation->value => 'Снижение рисков',
			self::TeamVelocity->value => 'Скорость команды',
			self::HeadcountManagement->value => 'Управление численностью персонала',
			self::EmployeeRetention->value => 'Удержание сотрудников',
			self::TrainingCompletion->value => 'Завершение обучения',
			self::WorkforceCostOptimization->value => 'Оптимизация затрат на персонал',
			self::SuccessionPlanning->value => 'Планирование преемственности',
			self::PerformanceReviewCompletion->value => 'Завершение оценки эффективности',
			self::EmployeeEngagement->value => 'Вовлеченность сотрудников',
			self::TimeToHire->value => 'Время найма',
			self::DiversityRatio->value => 'Коэффициент разнообразия',
			self::SystemUptime->value => 'Время безотказной работы системы',
			self::HelpDeskResolutionTime->value => 'Время решения службы поддержки',
			self::ProjectDeployment->value => 'Развертывание проекта',
			self::SecurityIncidentCount->value => 'Количество инцидентов безопасности',
			self::DataBackupSuccess->value => 'Успешность резервного копирования данных',
			self::SoftwareAssetOptimization->value => 'Оптимизация программных активов',
			self::NetworkPerformance->value => 'Производительность сети',
			self::IncidentResponseTime->value => 'Время реагирования на инциденты',
			self::InfrastructureCostPerUser->value => 'Стоимость инфраструктуры на пользователя',
			self::OperationalEfficiency->value => 'Операционная эффективность',
			self::StrategicInitiative->value => 'Стратегическая инициатива',
			self::PolicyCompliance->value => 'Соблюдение политик',
			self::FacilityManagement->value => 'Управление объектами',
			self::SustainabilityTarget->value => 'Цель устойчивого развития',
			self::VendorManagement->value => 'Управление поставщиками',
			self::DocumentControl->value => 'Контроль документов',
			self::BusinessContinuity->value => 'Непрерывность бизнеса',
		];
	}

	public static function labelsTr(): array
	{
		return [
			self::Invoice->value => 'Fatura',
			self::Bill->value => 'Fatura (satın alma)',
			self::Revenue->value => 'Gelir',
			self::Payment->value => 'Ödeme',
			self::GeneralLedgerAccuracy->value => 'Genel muhasebe doğruluğu',
			self::AccountsReceivableDays->value => 'Alacak günleri',
			self::AccountsPayableEfficiency->value => 'Borç verimliliği',
			self::CostReduction->value => 'Maliyet azaltma',
			self::BudgetAdherence->value => 'Bütçe uyumu',
			self::CashFlowTarget->value => 'Nakit akışı hedefi',
			self::AssetUtilization->value => 'Varlık kullanımı',
			self::AuditReadiness->value => 'Denetime hazırlık',
			self::TaxCompliance->value => 'Vergi uyumu',
			self::FinancialCloseTime->value => 'Finansal kapanış süresi',
			self::ExpenseRatio->value => 'Gider oranı',
			self::SalesQuota->value => 'Satış kotası',
			self::LeadConversion->value => 'Lead dönüşümü',
			self::CustomerAcquisitionCost->value => 'Müşteri edinme maliyeti',
			self::MarketShareGrowth->value => 'Pazar payı büyümesi',
			self::CustomerLifetimeValue->value => 'Müşteri yaşam boyu değeri',
			self::CampaignROI->value => 'Kampanya ROI',
			self::DealSize->value => 'Anlaşma büyüklüğü',
			self::SalesCycleLength->value => 'Satış döngüsü uzunluğu',
			self::PipelineValue->value => 'Satış kanalı değeri',
			self::MilestoneCompletion->value => 'Kilometre taşı tamamlanması',
			self::ProjectOnTime->value => 'Proje zamanında',
			self::ProjectOnBudget->value => 'Proje bütçe içinde',
			self::DeliverableQuality->value => 'Teslimat kalitesi',
			self::ScopeAdherence->value => 'Kapsam uyumu',
			self::StakeholderSatisfaction->value => 'Paydaş memnuniyeti',
			self::ResourceUtilization->value => 'Kaynak kullanımı',
			self::RiskMitigation->value => 'Risk azaltma',
			self::TeamVelocity->value => 'Takım hızı',
			self::HeadcountManagement->value => 'Personel yönetimi',
			self::EmployeeRetention->value => 'Çalışan bağlılığı',
			self::TrainingCompletion->value => 'Eğitim tamamlama',
			self::WorkforceCostOptimization->value => 'İş gücü maliyeti optimizasyonu',
			self::SuccessionPlanning->value => 'Halef planlaması',
			self::PerformanceReviewCompletion->value => 'Performans değerlendirme tamamlama',
			self::EmployeeEngagement->value => 'Çalışan katılımı',
			self::TimeToHire->value => 'İşe alım süresi',
			self::DiversityRatio->value => 'Çeşitlilik oranı',
			self::SystemUptime->value => 'Sistem çalışma süresi',
			self::HelpDeskResolutionTime->value => 'Help Desk çözüm süresi',
			self::ProjectDeployment->value => 'Proje dağıtımı',
			self::SecurityIncidentCount->value => 'Güvenlik olay sayısı',
			self::DataBackupSuccess->value => 'Veri yedekleme başarısı',
			self::SoftwareAssetOptimization->value => 'Yazılım varlık optimizasyonu',
			self::NetworkPerformance->value => 'Ağ performansı',
			self::IncidentResponseTime->value => 'Olay müdahale süresi',
			self::InfrastructureCostPerUser->value => 'Kullanıcı başına altyapı maliyeti',
			self::OperationalEfficiency->value => 'Operasyonel verimlilik',
			self::StrategicInitiative->value => 'Stratejik girişim',
			self::PolicyCompliance->value => 'Politika uyumu',
			self::FacilityManagement->value => 'Tesis yönetimi',
			self::SustainabilityTarget->value => 'Sürdürülebilirlik hedefi',
			self::VendorManagement->value => 'Tedarikçi yönetimi',
			self::DocumentControl->value => 'Doküman kontrolü',
			self::BusinessContinuity->value => 'İş sürekliliği',
		];
	}

	public static function labelsZh(): array
	{
		return [
			self::Invoice->value => '发票',
			self::Bill->value => '账单',
			self::Revenue->value => '收入',
			self::Payment->value => '付款',
			self::GeneralLedgerAccuracy->value => '总账准确性',
			self::AccountsReceivableDays->value => '应收账款天数',
			self::AccountsPayableEfficiency->value => '应付账款效率',
			self::CostReduction->value => '成本削减',
			self::BudgetAdherence->value => '预算遵守',
			self::CashFlowTarget->value => '现金流目标',
			self::AssetUtilization->value => '资产利用率',
			self::AuditReadiness->value => '审计准备',
			self::TaxCompliance->value => '税务合规',
			self::FinancialCloseTime->value => '财务结算时间',
			self::ExpenseRatio->value => '费用比率',
			self::SalesQuota->value => '销售配额',
			self::LeadConversion->value => '潜在客户转化',
			self::CustomerAcquisitionCost->value => '客户获取成本',
			self::MarketShareGrowth->value => '市场份额增长',
			self::CustomerLifetimeValue->value => '客户终身价值',
			self::CampaignROI->value => '营销活动投资回报率',
			self::DealSize->value => '交易规模',
			self::SalesCycleLength->value => '销售周期长度',
			self::PipelineValue->value => '销售渠道价值',
			self::MilestoneCompletion->value => '里程碑完成',
			self::ProjectOnTime->value => '项目按时完成',
			self::ProjectOnBudget->value => '项目预算内完成',
			self::DeliverableQuality->value => '交付物质量',
			self::ScopeAdherence->value => '范围遵守',
			self::StakeholderSatisfaction->value => '利益相关者满意度',
			self::ResourceUtilization->value => '资源利用率',
			self::RiskMitigation->value => '风险缓解',
			self::TeamVelocity->value => '团队速度',
			self::HeadcountManagement->value => '人员编制管理',
			self::EmployeeRetention->value => '员工留存率',
			self::TrainingCompletion->value => '培训完成率',
			self::WorkforceCostOptimization->value => '劳动力成本优化',
			self::SuccessionPlanning->value => '继任计划',
			self::PerformanceReviewCompletion->value => '绩效评估完成率',
			self::EmployeeEngagement->value => '员工敬业度',
			self::TimeToHire->value => '招聘时间',
			self::DiversityRatio->value => '多元化比率',
			self::SystemUptime->value => '系统运行时间',
			self::HelpDeskResolutionTime->value => '服务台解决时间',
			self::ProjectDeployment->value => '项目部署',
			self::SecurityIncidentCount->value => '安全事件数量',
			self::DataBackupSuccess->value => '数据备份成功率',
			self::SoftwareAssetOptimization->value => '软件资产优化',
			self::NetworkPerformance->value => '网络性能',
			self::IncidentResponseTime->value => '事件响应时间',
			self::InfrastructureCostPerUser->value => '每用户基础设施成本',
			self::OperationalEfficiency->value => '运营效率',
			self::StrategicInitiative->value => '战略倡议',
			self::PolicyCompliance->value => '政策合规',
			self::FacilityManagement->value => '设施管理',
			self::SustainabilityTarget->value => '可持续发展目标',
			self::VendorManagement->value => '供应商管理',
			self::DocumentControl->value => '文档控制',
			self::BusinessContinuity->value => '业务连续性',
		];
	}
}
