###############################################################################
# ERP Brand New Ideas Company — Namespace Kubernetes
# Namespace dedicado para isolar todos os recursos do ERP no cluster local.
###############################################################################
apiVersion: v1
kind: Namespace
metadata:
    name: erp-brand-new-ideas-company
    labels:
        app.kubernetes.io/part-of: erp-brand-new-ideas-company
        environment: local
