<?php

use App\Config\Constants\{ActivitiesConstants as AC, DatabaseConstants as DC, EmailsConstants as EC, UsersConstants as UC};
use App\Enums\ContactRole;
use App\Traits\HasNullableAuditColumns;
use Illuminate\Database\{Migrations\Migration, Schema\Blueprint};
use Illuminate\Support\Facades\{Log, Schema};

class CreateUserContactsTable extends Migration
{
    use HasNullableAuditColumns;
    private const TABLE = DC::TABLE_USR_CTT;
    public function up(): void
    {
        Schema::create(self::TABLE, function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid(UC::COL_USER_ID)->index();
            $table->uuid(EC::COL_PRT_ID)->nullable()->index(); // * it's never detailed what exactly is the "parent" here, but keeping for legacy, maybe it's the user owner of the contact, based on the contact() method from User; for this possibility, we must ensure that COL_USER_ID and COL_PRT_ID are not the same at model level
            $table->string('name', 254)->nullable()->unique(); // ? nullable for tests, should be autogenerated as an uuid at model level if not provided
            $table->uuid('company')->nullable()->index(); // ? must be enforced whereIn('type', ['company', 'vendor']), else nullified
            $table->enum('role', array_column(ContactRole::cases(), 'value'))->default(ContactRole::Other->value)->nullable();
            $table->string('email', 254)->nullable()->unique(); // ? at model level, at least one of email or phone is required, else throws
            $table->string('phone', 32)->nullable()->unique();
            $table->uuid(AC::COL_EM_ID)->nullable()->index(); // ? while the email column is literally an email address, the email can be saved in the system for more details
            $table->text('address')->nullable();
            $table->json(AC::COL_SC_MD)->nullable(); // ? filtered as an array containing direct urls for a valid social media domains, or an associative array with the keys (normalized) as the names of a recognized social media and some value in a inner key that has a valid social media domain url, else filtered out
            $table->text('notes')->nullable();
            $table->string('avatar', 254)->nullable();
            $table->date('birthday')->nullable();
            $table->boolean(AC::COL_IS_BLK)->default(false)->nullable()->index(); // ? nullable for tests, enforced at model level
            $table->boolean(AC::COL_IS_MT)->default(false)->nullable()->index(); // ? nullable for tests, enforced at model level // ? indicates if notifications related to this contact are muted
            $table->boolean(AC::COL_IS_FV)->default(false)->nullable()->index(); // ? nullable for tests, enforced at model level, automatically false if is_blocked is true
            $table->timestamp(AC::COL_LST_CT)->nullable()->index();
            $table->json('tags')->nullable();
            $table->json('templates')->nullable(); // ? list of ids for rows in the DC::TABLE_EMAIL_TEMPLATES or DC::TABLE_NOTIFICATION_TEMPLATES, useful for quick email sending (like for frequently contacted customers) or future notification automations, filtered by existing in the referred table
            $table->foreign(UC::COL_USER_ID)
                ->references('id')
                ->on(DC::TABLE_USERS)
                ->cascadeOnDelete();
            foreach (
                [
                    'company' => DC::TABLE_USERS,
                    EC::COL_PRT_ID => DC::TABLE_USERS,
                    AC::COL_EM_ID => DC::TABLE_EMAILS,
                ] as $column => $referencedTable
            )
                $table->foreign($column)
                    ->references('id')
                    ->on($referencedTable)
                    ->nullOnDelete();
            $this->addAuditColumns($table);
        });
    }

    public function down(): void
    {
        Schema::table(self::TABLE, function (Blueprint $table): void {
            $this->dropAuditColumnForeigns($table, self::TABLE);
            foreach (
                [
                    UC::COL_USER_ID,
                    AC::COL_EM_ID,
                    'company',
                    EC::COL_PRT_ID,
                ] as $column
            ) {
                try {
                    Schema::hasColumn(self::TABLE, $column)
                        && $table->dropForeign([$column]);
                } catch (\Exception $e) {
                    Log::warning(
                        'Failed to drop foreign key for '
                            . $column
                            . ' on table '
                            . self::TABLE
                            . ': '
                            . $e->getMessage()
                    );
                }
            }
        });
        Schema::dropIfExists(self::TABLE);
    }
}
